/*
 * Test pathsuffix.
 *
 * Copyright 2022 and 2023 Odin Kroeger.
 *
 * This file is part of suCGI.
 *
 * suCGI is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option)
 * any later version.
 *
 * suCGI is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with suCGI. If not, see <https://www.gnu.org/licenses>.
 */

#define _BSD_SOURCE
#define _DARWIN_C_SOURCE
#define _DEFAULT_SOURCE
#define _GNU_SOURCE

#include <err.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "../macros.h"
#include "../max.h"
#include "../path.h"
#include "result.h"


/*
 * Constants
 */

/* Maximum length of dynamically created pre- and suffixes. */
#define FIX_LEN 2U

/* Maximum length of dynamically created filenames. */
#define FNAME_LEN (FIX_LEN * 2U + 1U)


/*
 * Data types
 */

/* Mapping of filenames to return values. */
typedef struct {
    const char *const fname;
    const char *const suffix;
    const Error ret;
} Args;


/*
 * Module variables
 */

/* Test cases. */
static const Args cases[] = {
    {".", "<n/a>", ERR_SUFFIX},
    {"/", "<n/a>", ERR_SUFFIX},
    {"file.suffix", ".suffix", OK},
    {"file.very-long-suffix", ".very-long-suffix", OK},
    {"file.s", ".s", OK},
    {"file.", ".", OK},
    {"file", "<n/a>", ERR_SUFFIX},
    {".file", "<n/a>", ERR_SUFFIX},
    {"ḟïľē.şüḟḟï𝓍", ".şüḟḟï𝓍", OK},
    {"ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", OK},
    {"ḟïľē.ş", ".ş", OK},
    {"ḟïľē.", ".", OK},
    {"ḟïľē", "<n/a>", ERR_SUFFIX},
    {".ḟïľē", "<n/a>", ERR_SUFFIX},
    {"/file.suffix", ".suffix", OK},
    {"/file.very-long-suffix", ".very-long-suffix", OK},
    {"/file.s", ".s", OK},
    {"/file.", ".", OK},
    {"/file", "<n/a>", ERR_SUFFIX},
    {"/.file", "<n/a>", ERR_SUFFIX},
    {"/ḟïľē.şüḟḟï𝓍", ".şüḟḟï𝓍", OK},
    {"/ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", OK},
    {"/ḟïľē.ş", ".ş", OK},
    {"/ḟïľē.", ".", OK},
    {"/ḟïľē", "<n/a>", ERR_SUFFIX},
    {"/.ḟïľē", "<n/a>", ERR_SUFFIX},
    {"./file.suffix", ".suffix", OK},
    {"./file.very-long-suffix", ".very-long-suffix", OK},
    {"./file.s", ".s", OK},
    {"./file.", ".", OK},
    {"./file", "<n/a>", ERR_SUFFIX},
    {"./.file", "<n/a>", ERR_SUFFIX},
    {"./ḟïľē.şüḟḟï𝓍", ".şüḟḟï𝓍", OK},
    {"./ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", OK},
    {"./ḟïľē.ş", ".ş", OK},
    {"./ḟïľē.", ".", OK},
    {"./ḟïľē", "<n/a>", ERR_SUFFIX},
    {"./.ḟïľē", "<n/a>", ERR_SUFFIX},
    {"../file.suffix", ".suffix", OK},
    {"../file.very-long-suffix", ".very-long-suffix", OK},
    {"../file.s", ".s", OK},
    {"../file.", ".", OK},
    {"../file", "<n/a>", ERR_SUFFIX},
    {"../.file", "<n/a>", ERR_SUFFIX},
    {"../ḟïľē.şüḟḟï𝓍", ".şüḟḟï𝓍", OK},
    {"../ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", OK},
    {"../ḟïľē.ş", ".ş", OK},
    {"../ḟïľē.", ".", OK},
    {"../ḟïľē", "<n/a>", ERR_SUFFIX},
    {"../.ḟïľē", "<n/a>", ERR_SUFFIX},
    {"dir/file.suffix", ".suffix", OK},
    {"dir/file.very-long-suffix", ".very-long-suffix", OK},
    {"dir/file.s", ".s", OK},
    {"dir/file.", ".", OK},
    {"dir/file", "<n/a>", ERR_SUFFIX},
    {"dir/.file", "<n/a>", ERR_SUFFIX},
    {"ⓓïȓ/ḟïľē.şüḟḟï𝓍", ".şüḟḟï𝓍", OK},
    {"ⓓïȓ/ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", OK},
    {"ⓓïȓ/ḟïľē.ş", ".ş", OK},
    {"ⓓïȓ/ḟïľē.", ".", OK},
    {"ⓓïȓ/ḟïľē", "<n/a>", ERR_SUFFIX},
    {"ⓓïȓ/.ḟïľē", "<n/a>", ERR_SUFFIX},
    {"/dir/file.suffix", ".suffix", OK},
    {"/dir/file.very-long-suffix", ".very-long-suffix", OK},
    {"/dir/file.s", ".s", OK},
    {"/dir/file.", ".", OK},
    {"/dir/file", "<n/a>", ERR_SUFFIX},
    {"/dir/.file", "<n/a>", ERR_SUFFIX},
    {"/ⓓïȓ/ḟïľē.şüḟḟï𝓍", ".şüḟḟï𝓍", OK},
    {"/ⓓïȓ/ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", OK},
    {"/ⓓïȓ/ḟïľē.ş", ".ş", OK},
    {"/ⓓïȓ/ḟïľē.", ".", OK},
    {"/ⓓïȓ/ḟïľē", "<n/a>", ERR_SUFFIX},
    {"/ⓓïȓ/.ḟïľē", "<n/a>", ERR_SUFFIX},
    {"./dir/file.suffix", ".suffix", OK},
    {"./dir/file.very-long-suffix", ".very-long-suffix", OK},
    {"./dir/file.s", ".s", OK},
    {"./dir/file.", ".", OK},
    {"./dir/file", "<n/a>", ERR_SUFFIX},
    {"./dir/.file", "<n/a>", ERR_SUFFIX},
    {"./ⓓïȓ/ḟïľē.şüḟḟï𝓍", ".şüḟḟï𝓍", OK},
    {"./ⓓïȓ/ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", OK},
    {"./ⓓïȓ/ḟïľē.ş", ".ş", OK},
    {"./ⓓïȓ/ḟïľē.", ".", OK},
    {"./ⓓïȓ/ḟïľē", "<n/a>", ERR_SUFFIX},
    {"./ⓓïȓ/.ḟïľē", "<n/a>", ERR_SUFFIX},
    {"../dir/file.suffix", ".suffix", OK},
    {"../dir/file.very-long-suffix", ".very-long-suffix", OK},
    {"../dir/file.s", ".s", OK},
    {"../dir/file.", ".", OK},
    {"../dir/file", "<n/a>", ERR_SUFFIX},
    {"../dir/.file", "<n/a>", ERR_SUFFIX},
    {"../ⓓïȓ/ḟïľē.şüḟḟï𝓍", ".şüḟḟï𝓍", OK},
    {"../ⓓïȓ/ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", OK},
    {"../ⓓïȓ/ḟïľē.ş", ".ş", OK},
    {"../ⓓïȓ/ḟïľē.", ".", OK},
    {"../ⓓïȓ/ḟïľē", "<n/a>", ERR_SUFFIX},
    {"../ⓓïȓ/.ḟïľē", "<n/a>", ERR_SUFFIX},
    {"dir.suffix/file.suffix", ".suffix", OK},
    {"dir.suffix/file.very-long-suffix", ".very-long-suffix", OK},
    {"dir.suffix/file.s", ".s", OK},
    {"dir.suffix/file.", ".", OK},
    {"dir.suffix/file", "<n/a>", ERR_SUFFIX},
    {"dir.suffix/.file", "<n/a>", ERR_SUFFIX},
    {"ⓓïȓ.şüḟḟï𝓍/ḟïľē.şüḟḟï𝓍", ".şüḟḟï𝓍", OK},
    {"ⓓïȓ.şüḟḟï𝓍/ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", OK},
    {"ⓓïȓ.şüḟḟï𝓍/ḟïľē.ş", ".ş", OK},
    {"ⓓïȓ.şüḟḟï𝓍/ḟïľē.", ".", OK},
    {"ⓓïȓ.şüḟḟï𝓍/ḟïľē", "<n/a>", ERR_SUFFIX},
    {"ⓓïȓ.şüḟḟï𝓍/.ḟïľē", "<n/a>", ERR_SUFFIX},
    {"/dir.suffix/file.suffix", ".suffix", OK},
    {"/dir.suffix/file.very-long-suffix", ".very-long-suffix", OK},
    {"/dir.suffix/file.s", ".s", OK},
    {"/dir.suffix/file.", ".", OK},
    {"/dir.suffix/file", "<n/a>", ERR_SUFFIX},
    {"/dir.suffix/.file", "<n/a>", ERR_SUFFIX},
    {"/ⓓïȓ.şüḟḟï𝓍/ḟïľē.şüḟḟï𝓍", ".şüḟḟï𝓍", OK},
    {"/ⓓïȓ.şüḟḟï𝓍/ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", OK},
    {"/ⓓïȓ.şüḟḟï𝓍/ḟïľē.ş", ".ş", OK},
    {"/ⓓïȓ.şüḟḟï𝓍/ḟïľē.", ".", OK},
    {"/ⓓïȓ.şüḟḟï𝓍/ḟïľē", "<n/a>", ERR_SUFFIX},
    {"/ⓓïȓ.şüḟḟï𝓍/.ḟïľē", "<n/a>", ERR_SUFFIX},
    {"./dir.suffix/file.suffix", ".suffix", OK},
    {"./dir.suffix/file.very-long-suffix", ".very-long-suffix", OK},
    {"./dir.suffix/file.s", ".s", OK},
    {"./dir.suffix/file.", ".", OK},
    {"./dir.suffix/file", "<n/a>", ERR_SUFFIX},
    {"./dir.suffix/.file", "<n/a>", ERR_SUFFIX},
    {"./ⓓïȓ.şüḟḟï𝓍/ḟïľē.şüḟḟï𝓍", ".şüḟḟï𝓍", OK},
    {"./ⓓïȓ.şüḟḟï𝓍/ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", OK},
    {"./ⓓïȓ.şüḟḟï𝓍/ḟïľē.ş", ".ş", OK},
    {"./ⓓïȓ.şüḟḟï𝓍/ḟïľē.", ".", OK},
    {"./ⓓïȓ.şüḟḟï𝓍/ḟïľē", "<n/a>", ERR_SUFFIX},
    {"./ⓓïȓ.şüḟḟï𝓍/.ḟïľē", "<n/a>", ERR_SUFFIX},
    {"../dir.suffix/file.suffix", ".suffix", OK},
    {"../dir.suffix/file.very-long-suffix", ".very-long-suffix", OK},
    {"../dir.suffix/file.s", ".s", OK},
    {"../dir.suffix/file.", ".", OK},
    {"../dir.suffix/file", "<n/a>", ERR_SUFFIX},
    {"../dir.suffix/.file", "<n/a>", ERR_SUFFIX},
    {"../ⓓïȓ.şüḟḟï𝓍/ḟïľē.şüḟḟï𝓍", ".şüḟḟï𝓍", OK},
    {"../ⓓïȓ.şüḟḟï𝓍/ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", OK},
    {"../ⓓïȓ.şüḟḟï𝓍/ḟïľē.ş", ".ş", OK},
    {"../ⓓïȓ.şüḟḟï𝓍/ḟïľē.", ".", OK},
    {"../ⓓïȓ.şüḟḟï𝓍/ḟïľē", "<n/a>", ERR_SUFFIX},
    {"../ⓓïȓ.şüḟḟï𝓍/.ḟïľē", "<n/a>", ERR_SUFFIX},
    {"dir/./file.suffix", ".suffix", OK},
    {"dir/./file.very-long-suffix", ".very-long-suffix", OK},
    {"dir/./file.s", ".s", OK},
    {"dir/./file.", ".", OK},
    {"dir/./file", "<n/a>", ERR_SUFFIX},
    {"dir/./.file", "<n/a>", ERR_SUFFIX},
    {"ⓓïȓ/./ḟïľē.şüḟḟï𝓍", ".şüḟḟï𝓍", OK},
    {"ⓓïȓ/./ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", OK},
    {"ⓓïȓ/./ḟïľē.ş", ".ş", OK},
    {"ⓓïȓ/./ḟïľē.", ".", OK},
    {"ⓓïȓ/./ḟïľē", "<n/a>", ERR_SUFFIX},
    {"ⓓïȓ/./.ḟïľē", "<n/a>", ERR_SUFFIX},
    {"/./dir/./file.suffix", ".suffix", OK},
    {"/./dir/./file.very-long-suffix", ".very-long-suffix", OK},
    {"/./dir/./file.s", ".s", OK},
    {"/./dir/./file.", ".", OK},
    {"/./dir/./file", "<n/a>", ERR_SUFFIX},
    {"/./dir/./.file", "<n/a>", ERR_SUFFIX},
    {"/./ⓓïȓ/./ḟïľē.şüḟḟï𝓍", ".şüḟḟï𝓍", OK},
    {"/./ⓓïȓ/./ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", OK},
    {"/./ⓓïȓ/./ḟïľē.ş", ".ş", OK},
    {"/./ⓓïȓ/./ḟïľē.", ".", OK},
    {"/./ⓓïȓ/./ḟïľē", "<n/a>", ERR_SUFFIX},
    {"/./ⓓïȓ/./.ḟïľē", "<n/a>", ERR_SUFFIX},
    {"././dir/./file.suffix", ".suffix", OK},
    {"././dir/./file.very-long-suffix", ".very-long-suffix", OK},
    {"././dir/./file.s", ".s", OK},
    {"././dir/./file.", ".", OK},
    {"././dir/./file", "<n/a>", ERR_SUFFIX},
    {"././dir/./.file", "<n/a>", ERR_SUFFIX},
    {"././ⓓïȓ/./ḟïľē.şüḟḟï𝓍", ".şüḟḟï𝓍", OK},
    {"././ⓓïȓ/./ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", OK},
    {"././ⓓïȓ/./ḟïľē.ş", ".ş", OK},
    {"././ⓓïȓ/./ḟïľē.", ".", OK},
    {"././ⓓïȓ/./ḟïľē", "<n/a>", ERR_SUFFIX},
    {"././ⓓïȓ/./.ḟïľē", "<n/a>", ERR_SUFFIX},
    {".././dir/./file.suffix", ".suffix", OK},
    {".././dir/./file.very-long-suffix", ".very-long-suffix", OK},
    {".././dir/./file.s", ".s", OK},
    {".././dir/./file.", ".", OK},
    {".././dir/./file", "<n/a>", ERR_SUFFIX},
    {".././dir/./.file", "<n/a>", ERR_SUFFIX},
    {".././ⓓïȓ/./ḟïľē.şüḟḟï𝓍", ".şüḟḟï𝓍", OK},
    {".././ⓓïȓ/./ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", OK},
    {".././ⓓïȓ/./ḟïľē.ş", ".ş", OK},
    {".././ⓓïȓ/./ḟïľē.", ".", OK},
    {".././ⓓïȓ/./ḟïľē", "<n/a>", ERR_SUFFIX},
    {".././ⓓïȓ/./.ḟïľē", "<n/a>", ERR_SUFFIX},
    {"dir.suffix/./file.suffix", ".suffix", OK},
    {"dir.suffix/./file.very-long-suffix", ".very-long-suffix", OK},
    {"dir.suffix/./file.s", ".s", OK},
    {"dir.suffix/./file.", ".", OK},
    {"dir.suffix/./file", "<n/a>", ERR_SUFFIX},
    {"dir.suffix/./.file", "<n/a>", ERR_SUFFIX},
    {"ⓓïȓ.şüḟḟï𝓍/./ḟïľē.şüḟḟï𝓍", ".şüḟḟï𝓍", OK},
    {"ⓓïȓ.şüḟḟï𝓍/./ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", OK},
    {"ⓓïȓ.şüḟḟï𝓍/./ḟïľē.ş", ".ş", OK},
    {"ⓓïȓ.şüḟḟï𝓍/./ḟïľē.", ".", OK},
    {"ⓓïȓ.şüḟḟï𝓍/./ḟïľē", "<n/a>", ERR_SUFFIX},
    {"ⓓïȓ.şüḟḟï𝓍/./.ḟïľē", "<n/a>", ERR_SUFFIX},
    {"/./dir.suffix/./file.suffix", ".suffix", OK},
    {"/./dir.suffix/./file.very-long-suffix", ".very-long-suffix", OK},
    {"/./dir.suffix/./file.s", ".s", OK},
    {"/./dir.suffix/./file.", ".", OK},
    {"/./dir.suffix/./file", "<n/a>", ERR_SUFFIX},
    {"/./dir.suffix/./.file", "<n/a>", ERR_SUFFIX},
    {"/./ⓓïȓ.şüḟḟï𝓍/./ḟïľē.şüḟḟï𝓍", ".şüḟḟï𝓍", OK},
    {"/./ⓓïȓ.şüḟḟï𝓍/./ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", OK},
    {"/./ⓓïȓ.şüḟḟï𝓍/./ḟïľē.ş", ".ş", OK},
    {"/./ⓓïȓ.şüḟḟï𝓍/./ḟïľē.", ".", OK},
    {"/./ⓓïȓ.şüḟḟï𝓍/./ḟïľē", "<n/a>", ERR_SUFFIX},
    {"/./ⓓïȓ.şüḟḟï𝓍/./.ḟïľē", "<n/a>", ERR_SUFFIX},
    {"././dir.suffix/./file.suffix", ".suffix", OK},
    {"././dir.suffix/./file.very-long-suffix", ".very-long-suffix", OK},
    {"././dir.suffix/./file.s", ".s", OK},
    {"././dir.suffix/./file.", ".", OK},
    {"././dir.suffix/./file", "<n/a>", ERR_SUFFIX},
    {"././dir.suffix/./.file", "<n/a>", ERR_SUFFIX},
    {"././ⓓïȓ.şüḟḟï𝓍/./ḟïľē.şüḟḟï𝓍", ".şüḟḟï𝓍", OK},
    {"././ⓓïȓ.şüḟḟï𝓍/./ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", OK},
    {"././ⓓïȓ.şüḟḟï𝓍/./ḟïľē.ş", ".ş", OK},
    {"././ⓓïȓ.şüḟḟï𝓍/./ḟïľē.", ".", OK},
    {"././ⓓïȓ.şüḟḟï𝓍/./ḟïľē", "<n/a>", ERR_SUFFIX},
    {"././ⓓïȓ.şüḟḟï𝓍/./.ḟïľē", "<n/a>", ERR_SUFFIX},
    {".././dir.suffix/./file.suffix", ".suffix", OK},
    {".././dir.suffix/./file.very-long-suffix", ".very-long-suffix", OK},
    {".././dir.suffix/./file.s", ".s", OK},
    {".././dir.suffix/./file.", ".", OK},
    {".././dir.suffix/./file", "<n/a>", ERR_SUFFIX},
    {".././dir.suffix/./.file", "<n/a>", ERR_SUFFIX},
    {".././ⓓïȓ.şüḟḟï𝓍/./ḟïľē.şüḟḟï𝓍", ".şüḟḟï𝓍", OK},
    {".././ⓓïȓ.şüḟḟï𝓍/./ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", OK},
    {".././ⓓïȓ.şüḟḟï𝓍/./ḟïľē.ş", ".ş", OK},
    {".././ⓓïȓ.şüḟḟï𝓍/./ḟïľē.", ".", OK},
    {".././ⓓïȓ.şüḟḟï𝓍/./ḟïľē", "<n/a>", ERR_SUFFIX},
    {".././ⓓïȓ.şüḟḟï𝓍/./.ḟïľē", "<n/a>", ERR_SUFFIX},
    {"/../dir/../file.suffix", ".suffix", OK},
    {"/../dir/../file.very-long-suffix", ".very-long-suffix", OK},
    {"/../dir/../file.s", ".s", OK},
    {"/../dir/../file.", ".", OK},
    {"/../dir/../file", "<n/a>", ERR_SUFFIX},
    {"/../dir/../.file", "<n/a>", ERR_SUFFIX},
    {"/../ⓓïȓ/../ḟïľē.şüḟḟï𝓍", ".şüḟḟï𝓍", OK},
    {"/../ⓓïȓ/../ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", OK},
    {"/../ⓓïȓ/../ḟïľē.ş", ".ş", OK},
    {"/../ⓓïȓ/../ḟïľē.", ".", OK},
    {"/../ⓓïȓ/../ḟïľē", "<n/a>", ERR_SUFFIX},
    {"/../ⓓïȓ/../.ḟïľē", "<n/a>", ERR_SUFFIX},
    {"./../dir/../file.suffix", ".suffix", OK},
    {"./../dir/../file.very-long-suffix", ".very-long-suffix", OK},
    {"./../dir/../file.s", ".s", OK},
    {"./../dir/../file.", ".", OK},
    {"./../dir/../file", "<n/a>", ERR_SUFFIX},
    {"./../dir/../.file", "<n/a>", ERR_SUFFIX},
    {"./../ⓓïȓ/../ḟïľē.şüḟḟï𝓍", ".şüḟḟï𝓍", OK},
    {"./../ⓓïȓ/../ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", OK},
    {"./../ⓓïȓ/../ḟïľē.ş", ".ş", OK},
    {"./../ⓓïȓ/../ḟïľē.", ".", OK},
    {"./../ⓓïȓ/../ḟïľē", "<n/a>", ERR_SUFFIX},
    {"./../ⓓïȓ/../.ḟïľē", "<n/a>", ERR_SUFFIX},
    {"../../dir/../file.suffix", ".suffix", OK},
    {"../../dir/../file.very-long-suffix", ".very-long-suffix", OK},
    {"../../dir/../file.s", ".s", OK},
    {"../../dir/../file.", ".", OK},
    {"../../dir/../file", "<n/a>", ERR_SUFFIX},
    {"../../dir/../.file", "<n/a>", ERR_SUFFIX},
    {"../../ⓓïȓ/../ḟïľē.şüḟḟï𝓍", ".şüḟḟï𝓍", OK},
    {"../../ⓓïȓ/../ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", OK},
    {"../../ⓓïȓ/../ḟïľē.ş", ".ş", OK},
    {"../../ⓓïȓ/../ḟïľē.", ".", OK},
    {"../../ⓓïȓ/../ḟïľē", "<n/a>", ERR_SUFFIX},
    {"../../ⓓïȓ/../.ḟïľē", "<n/a>", ERR_SUFFIX},
    {"dir.suffix/../file.suffix", ".suffix", OK},
    {"dir.suffix/../file.very-long-suffix", ".very-long-suffix", OK},
    {"dir.suffix/../file.s", ".s", OK},
    {"dir.suffix/../file.", ".", OK},
    {"dir.suffix/../file", "<n/a>", ERR_SUFFIX},
    {"dir.suffix/../.file", "<n/a>", ERR_SUFFIX},
    {"ⓓïȓ.şüḟḟï𝓍/../ḟïľē.şüḟḟï𝓍", ".şüḟḟï𝓍", OK},
    {"ⓓïȓ.şüḟḟï𝓍/../ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", OK},
    {"ⓓïȓ.şüḟḟï𝓍/../ḟïľē.ş", ".ş", OK},
    {"ⓓïȓ.şüḟḟï𝓍/../ḟïľē.", ".", OK},
    {"ⓓïȓ.şüḟḟï𝓍/../ḟïľē", "<n/a>", ERR_SUFFIX},
    {"ⓓïȓ.şüḟḟï𝓍/../.ḟïľē", "<n/a>", ERR_SUFFIX},
    {"/../dir.suffix/../file.suffix", ".suffix", OK},
    {"/../dir.suffix/../file.very-long-suffix", ".very-long-suffix", OK},
    {"/../dir.suffix/../file.s", ".s", OK},
    {"/../dir.suffix/../file.", ".", OK},
    {"/../dir.suffix/../file", "<n/a>", ERR_SUFFIX},
    {"/../dir.suffix/../.file", "<n/a>", ERR_SUFFIX},
    {"/../ⓓïȓ.şüḟḟï𝓍/../ḟïľē.şüḟḟï𝓍", ".şüḟḟï𝓍", OK},
    {"/../ⓓïȓ.şüḟḟï𝓍/../ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", OK},
    {"/../ⓓïȓ.şüḟḟï𝓍/../ḟïľē.ş", ".ş", OK},
    {"/../ⓓïȓ.şüḟḟï𝓍/../ḟïľē.", ".", OK},
    {"/../ⓓïȓ.şüḟḟï𝓍/../ḟïľē", "<n/a>", ERR_SUFFIX},
    {"/../ⓓïȓ.şüḟḟï𝓍/../.ḟïľē", "<n/a>", ERR_SUFFIX},
    {"./../dir.suffix/../file.suffix", ".suffix", OK},
    {"./../dir.suffix/../file.very-long-suffix", ".very-long-suffix", OK},
    {"./../dir.suffix/../file.s", ".s", OK},
    {"./../dir.suffix/../file.", ".", OK},
    {"./../dir.suffix/../file", "<n/a>", ERR_SUFFIX},
    {"./../dir.suffix/../.file", "<n/a>", ERR_SUFFIX},
    {"./../ⓓïȓ.şüḟḟï𝓍/../ḟïľē.şüḟḟï𝓍", ".şüḟḟï𝓍", OK},
    {"./../ⓓïȓ.şüḟḟï𝓍/../ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", OK},
    {"./../ⓓïȓ.şüḟḟï𝓍/../ḟïľē.ş", ".ş", OK},
    {"./../ⓓïȓ.şüḟḟï𝓍/../ḟïľē.", ".", OK},
    {"./../ⓓïȓ.şüḟḟï𝓍/../ḟïľē", "<n/a>", ERR_SUFFIX},
    {"./../ⓓïȓ.şüḟḟï𝓍/../.ḟïľē", "<n/a>", ERR_SUFFIX},
    {"../../dir.suffix/../file.suffix", ".suffix", OK},
    {"../../dir.suffix/../file.very-long-suffix", ".very-long-suffix", OK},
    {"../../dir.suffix/../file.s", ".s", OK},
    {"../../dir.suffix/../file.", ".", OK},
    {"../../dir.suffix/../file", "<n/a>", ERR_SUFFIX},
    {"../../dir.suffix/../.file", "<n/a>", ERR_SUFFIX},
    {"../../ⓓïȓ.şüḟḟï𝓍/../ḟïľē.şüḟḟï𝓍", ".şüḟḟï𝓍", OK},
    {"../../ⓓïȓ.şüḟḟï𝓍/../ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", OK},
    {"../../ⓓïȓ.şüḟḟï𝓍/../ḟïľē.ş", ".ş", OK},
    {"../../ⓓïȓ.şüḟḟï𝓍/../ḟïľē.", ".", OK},
    {"../../ⓓïȓ.şüḟḟï𝓍/../ḟïľē", "<n/a>", ERR_SUFFIX},
    {"../../ⓓïȓ.şüḟḟï𝓍/../.ḟïľē", "<n/a>", ERR_SUFFIX},
    {".///", "<n/a>", ERR_SUFFIX},
    {"////", "<n/a>", ERR_SUFFIX},
    {"file.suffix///", ".suffix///", OK},
    {"file.very-long-suffix///", ".very-long-suffix///", OK},
    {"file.s///", ".s///", OK},
    {"file.///", ".///", OK},
    {"file///", "<n/a>", ERR_SUFFIX},
    {".file///", "<n/a>", ERR_SUFFIX},
    {"ḟïľē.şüḟḟï𝓍///", ".şüḟḟï𝓍///", OK},
    {"ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", OK},
    {"ḟïľē.ş///", ".ş///", OK},
    {"ḟïľē.///", ".///", OK},
    {"ḟïľē///", "<n/a>", ERR_SUFFIX},
    {".ḟïľē///", "<n/a>", ERR_SUFFIX},
    {"/file.suffix///", ".suffix///", OK},
    {"/file.very-long-suffix///", ".very-long-suffix///", OK},
    {"/file.s///", ".s///", OK},
    {"/file.///", ".///", OK},
    {"/file///", "<n/a>", ERR_SUFFIX},
    {"/.file///", "<n/a>", ERR_SUFFIX},
    {"/ḟïľē.şüḟḟï𝓍///", ".şüḟḟï𝓍///", OK},
    {"/ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", OK},
    {"/ḟïľē.ş///", ".ş///", OK},
    {"/ḟïľē.///", ".///", OK},
    {"/ḟïľē///", "<n/a>", ERR_SUFFIX},
    {"/.ḟïľē///", "<n/a>", ERR_SUFFIX},
    {"./file.suffix///", ".suffix///", OK},
    {"./file.very-long-suffix///", ".very-long-suffix///", OK},
    {"./file.s///", ".s///", OK},
    {"./file.///", ".///", OK},
    {"./file///", "<n/a>", ERR_SUFFIX},
    {"./.file///", "<n/a>", ERR_SUFFIX},
    {"./ḟïľē.şüḟḟï𝓍///", ".şüḟḟï𝓍///", OK},
    {"./ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", OK},
    {"./ḟïľē.ş///", ".ş///", OK},
    {"./ḟïľē.///", ".///", OK},
    {"./ḟïľē///", "<n/a>", ERR_SUFFIX},
    {"./.ḟïľē///", "<n/a>", ERR_SUFFIX},
    {"../file.suffix///", ".suffix///", OK},
    {"../file.very-long-suffix///", ".very-long-suffix///", OK},
    {"../file.s///", ".s///", OK},
    {"../file.///", ".///", OK},
    {"../file///", "<n/a>", ERR_SUFFIX},
    {"../.file///", "<n/a>", ERR_SUFFIX},
    {"../ḟïľē.şüḟḟï𝓍///", ".şüḟḟï𝓍///", OK},
    {"../ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", OK},
    {"../ḟïľē.ş///", ".ş///", OK},
    {"../ḟïľē.///", ".///", OK},
    {"../ḟïľē///", "<n/a>", ERR_SUFFIX},
    {"../.ḟïľē///", "<n/a>", ERR_SUFFIX},
    {"dir/file.suffix///", ".suffix///", OK},
    {"dir/file.very-long-suffix///", ".very-long-suffix///", OK},
    {"dir/file.s///", ".s///", OK},
    {"dir/file.///", ".///", OK},
    {"dir/file///", "<n/a>", ERR_SUFFIX},
    {"dir/.file///", "<n/a>", ERR_SUFFIX},
    {"ⓓïȓ/ḟïľē.şüḟḟï𝓍///", ".şüḟḟï𝓍///", OK},
    {"ⓓïȓ/ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", OK},
    {"ⓓïȓ/ḟïľē.ş///", ".ş///", OK},
    {"ⓓïȓ/ḟïľē.///", ".///", OK},
    {"ⓓïȓ/ḟïľē///", "<n/a>", ERR_SUFFIX},
    {"ⓓïȓ/.ḟïľē///", "<n/a>", ERR_SUFFIX},
    {"/dir/file.suffix///", ".suffix///", OK},
    {"/dir/file.very-long-suffix///", ".very-long-suffix///", OK},
    {"/dir/file.s///", ".s///", OK},
    {"/dir/file.///", ".///", OK},
    {"/dir/file///", "<n/a>", ERR_SUFFIX},
    {"/dir/.file///", "<n/a>", ERR_SUFFIX},
    {"/ⓓïȓ/ḟïľē.şüḟḟï𝓍///", ".şüḟḟï𝓍///", OK},
    {"/ⓓïȓ/ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", OK},
    {"/ⓓïȓ/ḟïľē.ş///", ".ş///", OK},
    {"/ⓓïȓ/ḟïľē.///", ".///", OK},
    {"/ⓓïȓ/ḟïľē///", "<n/a>", ERR_SUFFIX},
    {"/ⓓïȓ/.ḟïľē///", "<n/a>", ERR_SUFFIX},
    {"./dir/file.suffix///", ".suffix///", OK},
    {"./dir/file.very-long-suffix///", ".very-long-suffix///", OK},
    {"./dir/file.s///", ".s///", OK},
    {"./dir/file.///", ".///", OK},
    {"./dir/file///", "<n/a>", ERR_SUFFIX},
    {"./dir/.file///", "<n/a>", ERR_SUFFIX},
    {"./ⓓïȓ/ḟïľē.şüḟḟï𝓍///", ".şüḟḟï𝓍///", OK},
    {"./ⓓïȓ/ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", OK},
    {"./ⓓïȓ/ḟïľē.ş///", ".ş///", OK},
    {"./ⓓïȓ/ḟïľē.///", ".///", OK},
    {"./ⓓïȓ/ḟïľē///", "<n/a>", ERR_SUFFIX},
    {"./ⓓïȓ/.ḟïľē///", "<n/a>", ERR_SUFFIX},
    {"../dir/file.suffix///", ".suffix///", OK},
    {"../dir/file.very-long-suffix///", ".very-long-suffix///", OK},
    {"../dir/file.s///", ".s///", OK},
    {"../dir/file.///", ".///", OK},
    {"../dir/file///", "<n/a>", ERR_SUFFIX},
    {"../dir/.file///", "<n/a>", ERR_SUFFIX},
    {"../ⓓïȓ/ḟïľē.şüḟḟï𝓍///", ".şüḟḟï𝓍///", OK},
    {"../ⓓïȓ/ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", OK},
    {"../ⓓïȓ/ḟïľē.ş///", ".ş///", OK},
    {"../ⓓïȓ/ḟïľē.///", ".///", OK},
    {"../ⓓïȓ/ḟïľē///", "<n/a>", ERR_SUFFIX},
    {"../ⓓïȓ/.ḟïľē///", "<n/a>", ERR_SUFFIX},
    {"dir.suffix/file.suffix///", ".suffix///", OK},
    {"dir.suffix/file.very-long-suffix///", ".very-long-suffix///", OK},
    {"dir.suffix/file.s///", ".s///", OK},
    {"dir.suffix/file.///", ".///", OK},
    {"dir.suffix/file///", "<n/a>", ERR_SUFFIX},
    {"dir.suffix/.file///", "<n/a>", ERR_SUFFIX},
    {"ⓓïȓ.şüḟḟï𝓍/ḟïľē.şüḟḟï𝓍///", ".şüḟḟï𝓍///", OK},
    {"ⓓïȓ.şüḟḟï𝓍/ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", OK},
    {"ⓓïȓ.şüḟḟï𝓍/ḟïľē.ş///", ".ş///", OK},
    {"ⓓïȓ.şüḟḟï𝓍/ḟïľē.///", ".///", OK},
    {"ⓓïȓ.şüḟḟï𝓍/ḟïľē///", "<n/a>", ERR_SUFFIX},
    {"ⓓïȓ.şüḟḟï𝓍/.ḟïľē///", "<n/a>", ERR_SUFFIX},
    {"/dir.suffix/file.suffix///", ".suffix///", OK},
    {"/dir.suffix/file.very-long-suffix///", ".very-long-suffix///", OK},
    {"/dir.suffix/file.s///", ".s///", OK},
    {"/dir.suffix/file.///", ".///", OK},
    {"/dir.suffix/file///", "<n/a>", ERR_SUFFIX},
    {"/dir.suffix/.file///", "<n/a>", ERR_SUFFIX},
    {"/ⓓïȓ.şüḟḟï𝓍/ḟïľē.şüḟḟï𝓍///", ".şüḟḟï𝓍///", OK},
    {"/ⓓïȓ.şüḟḟï𝓍/ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", OK},
    {"/ⓓïȓ.şüḟḟï𝓍/ḟïľē.ş///", ".ş///", OK},
    {"/ⓓïȓ.şüḟḟï𝓍/ḟïľē.///", ".///", OK},
    {"/ⓓïȓ.şüḟḟï𝓍/ḟïľē///", "<n/a>", ERR_SUFFIX},
    {"/ⓓïȓ.şüḟḟï𝓍/.ḟïľē///", "<n/a>", ERR_SUFFIX},
    {"./dir.suffix/file.suffix///", ".suffix///", OK},
    {"./dir.suffix/file.very-long-suffix///", ".very-long-suffix///", OK},
    {"./dir.suffix/file.s///", ".s///", OK},
    {"./dir.suffix/file.///", ".///", OK},
    {"./dir.suffix/file///", "<n/a>", ERR_SUFFIX},
    {"./dir.suffix/.file///", "<n/a>", ERR_SUFFIX},
    {"./ⓓïȓ.şüḟḟï𝓍/ḟïľē.şüḟḟï𝓍///", ".şüḟḟï𝓍///", OK},
    {"./ⓓïȓ.şüḟḟï𝓍/ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", OK},
    {"./ⓓïȓ.şüḟḟï𝓍/ḟïľē.ş///", ".ş///", OK},
    {"./ⓓïȓ.şüḟḟï𝓍/ḟïľē.///", ".///", OK},
    {"./ⓓïȓ.şüḟḟï𝓍/ḟïľē///", "<n/a>", ERR_SUFFIX},
    {"./ⓓïȓ.şüḟḟï𝓍/.ḟïľē///", "<n/a>", ERR_SUFFIX},
    {"../dir.suffix/file.suffix///", ".suffix///", OK},
    {"../dir.suffix/file.very-long-suffix///", ".very-long-suffix///", OK},
    {"../dir.suffix/file.s///", ".s///", OK},
    {"../dir.suffix/file.///", ".///", OK},
    {"../dir.suffix/file///", "<n/a>", ERR_SUFFIX},
    {"../dir.suffix/.file///", "<n/a>", ERR_SUFFIX},
    {"../ⓓïȓ.şüḟḟï𝓍/ḟïľē.şüḟḟï𝓍///", ".şüḟḟï𝓍///", OK},
    {"../ⓓïȓ.şüḟḟï𝓍/ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", OK},
    {"../ⓓïȓ.şüḟḟï𝓍/ḟïľē.ş///", ".ş///", OK},
    {"../ⓓïȓ.şüḟḟï𝓍/ḟïľē.///", ".///", OK},
    {"../ⓓïȓ.şüḟḟï𝓍/ḟïľē///", "<n/a>", ERR_SUFFIX},
    {"../ⓓïȓ.şüḟḟï𝓍/.ḟïľē///", "<n/a>", ERR_SUFFIX},
    {"dir/./file.suffix///", ".suffix///", OK},
    {"dir/./file.very-long-suffix///", ".very-long-suffix///", OK},
    {"dir/./file.s///", ".s///", OK},
    {"dir/./file.///", ".///", OK},
    {"dir/./file///", "<n/a>", ERR_SUFFIX},
    {"dir/./.file///", "<n/a>", ERR_SUFFIX},
    {"ⓓïȓ/./ḟïľē.şüḟḟï𝓍///", ".şüḟḟï𝓍///", OK},
    {"ⓓïȓ/./ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", OK},
    {"ⓓïȓ/./ḟïľē.ş///", ".ş///", OK},
    {"ⓓïȓ/./ḟïľē.///", ".///", OK},
    {"ⓓïȓ/./ḟïľē///", "<n/a>", ERR_SUFFIX},
    {"ⓓïȓ/./.ḟïľē///", "<n/a>", ERR_SUFFIX},
    {"/./dir/./file.suffix///", ".suffix///", OK},
    {"/./dir/./file.very-long-suffix///", ".very-long-suffix///", OK},
    {"/./dir/./file.s///", ".s///", OK},
    {"/./dir/./file.///", ".///", OK},
    {"/./dir/./file///", "<n/a>", ERR_SUFFIX},
    {"/./dir/./.file///", "<n/a>", ERR_SUFFIX},
    {"/./ⓓïȓ/./ḟïľē.şüḟḟï𝓍///", ".şüḟḟï𝓍///", OK},
    {"/./ⓓïȓ/./ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", OK},
    {"/./ⓓïȓ/./ḟïľē.ş///", ".ş///", OK},
    {"/./ⓓïȓ/./ḟïľē.///", ".///", OK},
    {"/./ⓓïȓ/./ḟïľē///", "<n/a>", ERR_SUFFIX},
    {"/./ⓓïȓ/./.ḟïľē///", "<n/a>", ERR_SUFFIX},
    {"././dir/./file.suffix///", ".suffix///", OK},
    {"././dir/./file.very-long-suffix///", ".very-long-suffix///", OK},
    {"././dir/./file.s///", ".s///", OK},
    {"././dir/./file.///", ".///", OK},
    {"././dir/./file///", "<n/a>", ERR_SUFFIX},
    {"././dir/./.file///", "<n/a>", ERR_SUFFIX},
    {"././ⓓïȓ/./ḟïľē.şüḟḟï𝓍///", ".şüḟḟï𝓍///", OK},
    {"././ⓓïȓ/./ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", OK},
    {"././ⓓïȓ/./ḟïľē.ş///", ".ş///", OK},
    {"././ⓓïȓ/./ḟïľē.///", ".///", OK},
    {"././ⓓïȓ/./ḟïľē///", "<n/a>", ERR_SUFFIX},
    {"././ⓓïȓ/./.ḟïľē///", "<n/a>", ERR_SUFFIX},
    {".././dir/./file.suffix///", ".suffix///", OK},
    {".././dir/./file.very-long-suffix///", ".very-long-suffix///", OK},
    {".././dir/./file.s///", ".s///", OK},
    {".././dir/./file.///", ".///", OK},
    {".././dir/./file///", "<n/a>", ERR_SUFFIX},
    {".././dir/./.file///", "<n/a>", ERR_SUFFIX},
    {".././ⓓïȓ/./ḟïľē.şüḟḟï𝓍///", ".şüḟḟï𝓍///", OK},
    {".././ⓓïȓ/./ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", OK},
    {".././ⓓïȓ/./ḟïľē.ş///", ".ş///", OK},
    {".././ⓓïȓ/./ḟïľē.///", ".///", OK},
    {".././ⓓïȓ/./ḟïľē///", "<n/a>", ERR_SUFFIX},
    {".././ⓓïȓ/./.ḟïľē///", "<n/a>", ERR_SUFFIX},
    {"dir.suffix/./file.suffix///", ".suffix///", OK},
    {"dir.suffix/./file.very-long-suffix///", ".very-long-suffix///", OK},
    {"dir.suffix/./file.s///", ".s///", OK},
    {"dir.suffix/./file.///", ".///", OK},
    {"dir.suffix/./file///", "<n/a>", ERR_SUFFIX},
    {"dir.suffix/./.file///", "<n/a>", ERR_SUFFIX},
    {"ⓓïȓ.şüḟḟï𝓍/./ḟïľē.şüḟḟï𝓍///", ".şüḟḟï𝓍///", OK},
    {"ⓓïȓ.şüḟḟï𝓍/./ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", OK},
    {"ⓓïȓ.şüḟḟï𝓍/./ḟïľē.ş///", ".ş///", OK},
    {"ⓓïȓ.şüḟḟï𝓍/./ḟïľē.///", ".///", OK},
    {"ⓓïȓ.şüḟḟï𝓍/./ḟïľē///", "<n/a>", ERR_SUFFIX},
    {"ⓓïȓ.şüḟḟï𝓍/./.ḟïľē///", "<n/a>", ERR_SUFFIX},
    {"/./dir.suffix/./file.suffix///", ".suffix///", OK},
    {"/./dir.suffix/./file.very-long-suffix///", ".very-long-suffix///", OK},
    {"/./dir.suffix/./file.s///", ".s///", OK},
    {"/./dir.suffix/./file.///", ".///", OK},
    {"/./dir.suffix/./file///", "<n/a>", ERR_SUFFIX},
    {"/./dir.suffix/./.file///", "<n/a>", ERR_SUFFIX},
    {"/./ⓓïȓ.şüḟḟï𝓍/./ḟïľē.şüḟḟï𝓍///", ".şüḟḟï𝓍///", OK},
    {"/./ⓓïȓ.şüḟḟï𝓍/./ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", OK},
    {"/./ⓓïȓ.şüḟḟï𝓍/./ḟïľē.ş///", ".ş///", OK},
    {"/./ⓓïȓ.şüḟḟï𝓍/./ḟïľē.///", ".///", OK},
    {"/./ⓓïȓ.şüḟḟï𝓍/./ḟïľē///", "<n/a>", ERR_SUFFIX},
    {"/./ⓓïȓ.şüḟḟï𝓍/./.ḟïľē///", "<n/a>", ERR_SUFFIX},
    {"././dir.suffix/./file.suffix///", ".suffix///", OK},
    {"././dir.suffix/./file.very-long-suffix///", ".very-long-suffix///", OK},
    {"././dir.suffix/./file.s///", ".s///", OK},
    {"././dir.suffix/./file.///", ".///", OK},
    {"././dir.suffix/./file///", "<n/a>", ERR_SUFFIX},
    {"././dir.suffix/./.file///", "<n/a>", ERR_SUFFIX},
    {"././ⓓïȓ.şüḟḟï𝓍/./ḟïľē.şüḟḟï𝓍///", ".şüḟḟï𝓍///", OK},
    {"././ⓓïȓ.şüḟḟï𝓍/./ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", OK},
    {"././ⓓïȓ.şüḟḟï𝓍/./ḟïľē.ş///", ".ş///", OK},
    {"././ⓓïȓ.şüḟḟï𝓍/./ḟïľē.///", ".///", OK},
    {"././ⓓïȓ.şüḟḟï𝓍/./ḟïľē///", "<n/a>", ERR_SUFFIX},
    {"././ⓓïȓ.şüḟḟï𝓍/./.ḟïľē///", "<n/a>", ERR_SUFFIX},
    {".././dir.suffix/./file.suffix///", ".suffix///", OK},
    {".././dir.suffix/./file.very-long-suffix///", ".very-long-suffix///", OK},
    {".././dir.suffix/./file.s///", ".s///", OK},
    {".././dir.suffix/./file.///", ".///", OK},
    {".././dir.suffix/./file///", "<n/a>", ERR_SUFFIX},
    {".././dir.suffix/./.file///", "<n/a>", ERR_SUFFIX},
    {".././ⓓïȓ.şüḟḟï𝓍/./ḟïľē.şüḟḟï𝓍///", ".şüḟḟï𝓍///", OK},
    {".././ⓓïȓ.şüḟḟï𝓍/./ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", OK},
    {".././ⓓïȓ.şüḟḟï𝓍/./ḟïľē.ş///", ".ş///", OK},
    {".././ⓓïȓ.şüḟḟï𝓍/./ḟïľē.///", ".///", OK},
    {".././ⓓïȓ.şüḟḟï𝓍/./ḟïľē///", "<n/a>", ERR_SUFFIX},
    {".././ⓓïȓ.şüḟḟï𝓍/./.ḟïľē///", "<n/a>", ERR_SUFFIX},
    {"/../dir/../file.suffix///", ".suffix///", OK},
    {"/../dir/../file.very-long-suffix///", ".very-long-suffix///", OK},
    {"/../dir/../file.s///", ".s///", OK},
    {"/../dir/../file.///", ".///", OK},
    {"/../dir/../file///", "<n/a>", ERR_SUFFIX},
    {"/../dir/../.file///", "<n/a>", ERR_SUFFIX},
    {"/../ⓓïȓ/../ḟïľē.şüḟḟï𝓍///", ".şüḟḟï𝓍///", OK},
    {"/../ⓓïȓ/../ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", OK},
    {"/../ⓓïȓ/../ḟïľē.ş///", ".ş///", OK},
    {"/../ⓓïȓ/../ḟïľē.///", ".///", OK},
    {"/../ⓓïȓ/../ḟïľē///", "<n/a>", ERR_SUFFIX},
    {"/../ⓓïȓ/../.ḟïľē///", "<n/a>", ERR_SUFFIX},
    {"./../dir/../file.suffix///", ".suffix///", OK},
    {"./../dir/../file.very-long-suffix///", ".very-long-suffix///", OK},
    {"./../dir/../file.s///", ".s///", OK},
    {"./../dir/../file.///", ".///", OK},
    {"./../dir/../file///", "<n/a>", ERR_SUFFIX},
    {"./../dir/../.file///", "<n/a>", ERR_SUFFIX},
    {"./../ⓓïȓ/../ḟïľē.şüḟḟï𝓍///", ".şüḟḟï𝓍///", OK},
    {"./../ⓓïȓ/../ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", OK},
    {"./../ⓓïȓ/../ḟïľē.ş///", ".ş///", OK},
    {"./../ⓓïȓ/../ḟïľē.///", ".///", OK},
    {"./../ⓓïȓ/../ḟïľē///", "<n/a>", ERR_SUFFIX},
    {"./../ⓓïȓ/../.ḟïľē///", "<n/a>", ERR_SUFFIX},
    {"../../dir/../file.suffix///", ".suffix///", OK},
    {"../../dir/../file.very-long-suffix///", ".very-long-suffix///", OK},
    {"../../dir/../file.s///", ".s///", OK},
    {"../../dir/../file.///", ".///", OK},
    {"../../dir/../file///", "<n/a>", ERR_SUFFIX},
    {"../../dir/../.file///", "<n/a>", ERR_SUFFIX},
    {"../../ⓓïȓ/../ḟïľē.şüḟḟï𝓍///", ".şüḟḟï𝓍///", OK},
    {"../../ⓓïȓ/../ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", OK},
    {"../../ⓓïȓ/../ḟïľē.ş///", ".ş///", OK},
    {"../../ⓓïȓ/../ḟïľē.///", ".///", OK},
    {"../../ⓓïȓ/../ḟïľē///", "<n/a>", ERR_SUFFIX},
    {"../../ⓓïȓ/../.ḟïľē///", "<n/a>", ERR_SUFFIX},
    {"dir.suffix/../file.suffix///", ".suffix///", OK},
    {"dir.suffix/../file.very-long-suffix///", ".very-long-suffix///", OK},
    {"dir.suffix/../file.s///", ".s///", OK},
    {"dir.suffix/../file.///", ".///", OK},
    {"dir.suffix/../file///", "<n/a>", ERR_SUFFIX},
    {"dir.suffix/../.file///", "<n/a>", ERR_SUFFIX},
    {"ⓓïȓ.şüḟḟï𝓍/../ḟïľē.şüḟḟï𝓍///", ".şüḟḟï𝓍///", OK},
    {"ⓓïȓ.şüḟḟï𝓍/../ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", OK},
    {"ⓓïȓ.şüḟḟï𝓍/../ḟïľē.ş///", ".ş///", OK},
    {"ⓓïȓ.şüḟḟï𝓍/../ḟïľē.///", ".///", OK},
    {"ⓓïȓ.şüḟḟï𝓍/../ḟïľē///", "<n/a>", ERR_SUFFIX},
    {"ⓓïȓ.şüḟḟï𝓍/../.ḟïľē///", "<n/a>", ERR_SUFFIX},
    {"/../dir.suffix/../file.suffix///", ".suffix///", OK},
    {"/../dir.suffix/../file.very-long-suffix///", ".very-long-suffix///", OK},
    {"/../dir.suffix/../file.s///", ".s///", OK},
    {"/../dir.suffix/../file.///", ".///", OK},
    {"/../dir.suffix/../file///", "<n/a>", ERR_SUFFIX},
    {"/../dir.suffix/../.file///", "<n/a>", ERR_SUFFIX},
    {"/../ⓓïȓ.şüḟḟï𝓍/../ḟïľē.şüḟḟï𝓍///", ".şüḟḟï𝓍///", OK},
    {"/../ⓓïȓ.şüḟḟï𝓍/../ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", OK},
    {"/../ⓓïȓ.şüḟḟï𝓍/../ḟïľē.ş///", ".ş///", OK},
    {"/../ⓓïȓ.şüḟḟï𝓍/../ḟïľē.///", ".///", OK},
    {"/../ⓓïȓ.şüḟḟï𝓍/../ḟïľē///", "<n/a>", ERR_SUFFIX},
    {"/../ⓓïȓ.şüḟḟï𝓍/../.ḟïľē///", "<n/a>", ERR_SUFFIX},
    {"./../dir.suffix/../file.suffix///", ".suffix///", OK},
    {"./../dir.suffix/../file.very-long-suffix///", ".very-long-suffix///", OK},
    {"./../dir.suffix/../file.s///", ".s///", OK},
    {"./../dir.suffix/../file.///", ".///", OK},
    {"./../dir.suffix/../file///", "<n/a>", ERR_SUFFIX},
    {"./../dir.suffix/../.file///", "<n/a>", ERR_SUFFIX},
    {"./../ⓓïȓ.şüḟḟï𝓍/../ḟïľē.şüḟḟï𝓍///", ".şüḟḟï𝓍///", OK},
    {"./../ⓓïȓ.şüḟḟï𝓍/../ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", OK},
    {"./../ⓓïȓ.şüḟḟï𝓍/../ḟïľē.ş///", ".ş///", OK},
    {"./../ⓓïȓ.şüḟḟï𝓍/../ḟïľē.///", ".///", OK},
    {"./../ⓓïȓ.şüḟḟï𝓍/../ḟïľē///", "<n/a>", ERR_SUFFIX},
    {"./../ⓓïȓ.şüḟḟï𝓍/../.ḟïľē///", "<n/a>", ERR_SUFFIX},
    {"../../dir.suffix/../file.suffix///", ".suffix///", OK},
    {"../../dir.suffix/../file.very-long-suffix///", ".very-long-suffix///", OK},
    {"../../dir.suffix/../file.s///", ".s///", OK},
    {"../../dir.suffix/../file.///", ".///", OK},
    {"../../dir.suffix/../file///", "<n/a>", ERR_SUFFIX},
    {"../../dir.suffix/../.file///", "<n/a>", ERR_SUFFIX},
    {"../../ⓓïȓ.şüḟḟï𝓍/../ḟïľē.şüḟḟï𝓍///", ".şüḟḟï𝓍///", OK},
    {"../../ⓓïȓ.şüḟḟï𝓍/../ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", OK},
    {"../../ⓓïȓ.şüḟḟï𝓍/../ḟïľē.ş///", ".ş///", OK},
    {"../../ⓓïȓ.şüḟḟï𝓍/../ḟïľē.///", ".///", OK},
    {"../../ⓓïȓ.şüḟḟï𝓍/../ḟïľē///", "<n/a>", ERR_SUFFIX},
    {"../../ⓓïȓ.şüḟḟï𝓍/../.ḟïľē///", "<n/a>", ERR_SUFFIX}
};


/*
 * Main
 */

int
main (void)
{
    int result = TEST_PASSED;

    for (size_t i = 0; i < NELEMS(cases); ++i) {
        const Args args = cases[i];
        const char *suffix;
        Error ret;

        ret = pathsuffix(args.fname, &suffix);

        if (ret != args.ret) {
            warnx("(%s, -> %s) -> %u [!]",
                  args.fname, args.suffix, ret);
            result = TEST_FAILED;
        }

        if (ret == OK && strncmp(args.suffix, suffix, MAX_SUFFIX_LEN) != 0) {
            warnx("(%s, -> %s [!]) -> %u",
                  args.fname, suffix, args.ret);
            result = TEST_FAILED;
        }
    }

    return result;
}
