/*
 * Test pathsuffix.
 *
 * Copyright 2022 and 2023 Odin Kroeger.
 *
 * This file is part of suCGI.
 *
 * suCGI is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option)
 * any later version.
 *
 * suCGI is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with suCGI. If not, see <https://www.gnu.org/licenses>.
 */

#define _BSD_SOURCE
#define _DARWIN_C_SOURCE
#define _DEFAULT_SOURCE
#define _GNU_SOURCE

#include <err.h>
#include <setjmp.h>
#include <signal.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "../macros.h"
#include "../max.h"
#include "../path.h"
#include "lib/util.h"


/*
 * Data types
 */

/* Mapping of filenames to return values. */
typedef struct {
    const char *const fname;
    const char *const suffix;
    const Error retval;
    int signo;
} Args;


/*
 * Module variables
 */

#if !defined(NDEBUG)
/* A filename that that exceeds MAX_STR_LEN. */
static char hugefname[MAX_FNAME_LEN + 1U] = {0};
#endif

/* A filename just within MAX_FNAME_LEN */
static char longfname[MAX_FNAME_LEN] = {0};

/* Test cases. */
static const Args cases[] = {
    /* Illegal arguments. */
#if !defined(NDEBUG)
    {"", "<n/a>", OK, SIGABRT},
    {hugefname, "<n/a>", OK, SIGABRT},
#endif

    /* Long filename. */
    {longfname, "<n/a>", ERR_SUFFIX, 0},

    /* Various checks. */
    {".", "<n/a>", ERR_SUFFIX, 0},
    {"/", "<n/a>", ERR_SUFFIX, 0},
    {"file.sfx", ".sfx", OK, 0},
    {"file.very-long-suffix", ".very-long-suffix", OK, 0},
    {"file.s", ".s", OK, 0},
    {"file.", ".", OK, 0},
    {"file", "<n/a>", ERR_SUFFIX, 0},
    {".file", "<n/a>", ERR_SUFFIX, 0},
    {"ḟïľē.şḟ𝓍", ".şḟ𝓍", OK, 0},
    {"ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", OK, 0},
    {"ḟïľē.ş", ".ş", OK, 0},
    {"ḟïľē.", ".", OK, 0},
    {"ḟïľē", "<n/a>", ERR_SUFFIX, 0},
    {".ḟïľē", "<n/a>", ERR_SUFFIX, 0},
    {"/file.sfx", ".sfx", OK, 0},
    {"/file.very-long-suffix", ".very-long-suffix", OK, 0},
    {"/file.s", ".s", OK, 0},
    {"/file.", ".", OK, 0},
    {"/file", "<n/a>", ERR_SUFFIX, 0},
    {"/.file", "<n/a>", ERR_SUFFIX, 0},
    {"/ḟïľē.şḟ𝓍", ".şḟ𝓍", OK, 0},
    {"/ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", OK, 0},
    {"/ḟïľē.ş", ".ş", OK, 0},
    {"/ḟïľē.", ".", OK, 0},
    {"/ḟïľē", "<n/a>", ERR_SUFFIX, 0},
    {"/.ḟïľē", "<n/a>", ERR_SUFFIX, 0},
    {"./file.sfx", ".sfx", OK, 0},
    {"./file.very-long-suffix", ".very-long-suffix", OK, 0},
    {"./file.s", ".s", OK, 0},
    {"./file.", ".", OK, 0},
    {"./file", "<n/a>", ERR_SUFFIX, 0},
    {"./.file", "<n/a>", ERR_SUFFIX, 0},
    {"./ḟïľē.şḟ𝓍", ".şḟ𝓍", OK, 0},
    {"./ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", OK, 0},
    {"./ḟïľē.ş", ".ş", OK, 0},
    {"./ḟïľē.", ".", OK, 0},
    {"./ḟïľē", "<n/a>", ERR_SUFFIX, 0},
    {"./.ḟïľē", "<n/a>", ERR_SUFFIX, 0},
    {"../file.sfx", ".sfx", OK, 0},
    {"../file.very-long-suffix", ".very-long-suffix", OK, 0},
    {"../file.s", ".s", OK, 0},
    {"../file.", ".", OK, 0},
    {"../file", "<n/a>", ERR_SUFFIX, 0},
    {"../.file", "<n/a>", ERR_SUFFIX, 0},
    {"../ḟïľē.şḟ𝓍", ".şḟ𝓍", OK, 0},
    {"../ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", OK, 0},
    {"../ḟïľē.ş", ".ş", OK, 0},
    {"../ḟïľē.", ".", OK, 0},
    {"../ḟïľē", "<n/a>", ERR_SUFFIX, 0},
    {"../.ḟïľē", "<n/a>", ERR_SUFFIX, 0},
    {"dir/file.sfx", ".sfx", OK, 0},
    {"dir/file.very-long-suffix", ".very-long-suffix", OK, 0},
    {"dir/file.s", ".s", OK, 0},
    {"dir/file.", ".", OK, 0},
    {"dir/file", "<n/a>", ERR_SUFFIX, 0},
    {"dir/.file", "<n/a>", ERR_SUFFIX, 0},
    {"ⓓïȓ/ḟïľē.şḟ𝓍", ".şḟ𝓍", OK, 0},
    {"ⓓïȓ/ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", OK, 0},
    {"ⓓïȓ/ḟïľē.ş", ".ş", OK, 0},
    {"ⓓïȓ/ḟïľē.", ".", OK, 0},
    {"ⓓïȓ/ḟïľē", "<n/a>", ERR_SUFFIX, 0},
    {"ⓓïȓ/.ḟïľē", "<n/a>", ERR_SUFFIX, 0},
    {"/dir/file.sfx", ".sfx", OK, 0},
    {"/dir/file.very-long-suffix", ".very-long-suffix", OK, 0},
    {"/dir/file.s", ".s", OK, 0},
    {"/dir/file.", ".", OK, 0},
    {"/dir/file", "<n/a>", ERR_SUFFIX, 0},
    {"/dir/.file", "<n/a>", ERR_SUFFIX, 0},
    {"/ⓓïȓ/ḟïľē.şḟ𝓍", ".şḟ𝓍", OK, 0},
    {"/ⓓïȓ/ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", OK, 0},
    {"/ⓓïȓ/ḟïľē.ş", ".ş", OK, 0},
    {"/ⓓïȓ/ḟïľē.", ".", OK, 0},
    {"/ⓓïȓ/ḟïľē", "<n/a>", ERR_SUFFIX, 0},
    {"/ⓓïȓ/.ḟïľē", "<n/a>", ERR_SUFFIX, 0},
    {"./dir/file.sfx", ".sfx", OK, 0},
    {"./dir/file.very-long-suffix", ".very-long-suffix", OK, 0},
    {"./dir/file.s", ".s", OK, 0},
    {"./dir/file.", ".", OK, 0},
    {"./dir/file", "<n/a>", ERR_SUFFIX, 0},
    {"./dir/.file", "<n/a>", ERR_SUFFIX, 0},
    {"./ⓓïȓ/ḟïľē.şḟ𝓍", ".şḟ𝓍", OK, 0},
    {"./ⓓïȓ/ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", OK, 0},
    {"./ⓓïȓ/ḟïľē.ş", ".ş", OK, 0},
    {"./ⓓïȓ/ḟïľē.", ".", OK, 0},
    {"./ⓓïȓ/ḟïľē", "<n/a>", ERR_SUFFIX, 0},
    {"./ⓓïȓ/.ḟïľē", "<n/a>", ERR_SUFFIX, 0},
    {"../dir/file.sfx", ".sfx", OK, 0},
    {"../dir/file.very-long-suffix", ".very-long-suffix", OK, 0},
    {"../dir/file.s", ".s", OK, 0},
    {"../dir/file.", ".", OK, 0},
    {"../dir/file", "<n/a>", ERR_SUFFIX, 0},
    {"../dir/.file", "<n/a>", ERR_SUFFIX, 0},
    {"../ⓓïȓ/ḟïľē.şḟ𝓍", ".şḟ𝓍", OK, 0},
    {"../ⓓïȓ/ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", OK, 0},
    {"../ⓓïȓ/ḟïľē.ş", ".ş", OK, 0},
    {"../ⓓïȓ/ḟïľē.", ".", OK, 0},
    {"../ⓓïȓ/ḟïľē", "<n/a>", ERR_SUFFIX, 0},
    {"../ⓓïȓ/.ḟïľē", "<n/a>", ERR_SUFFIX, 0},
    {"dir.sfx/file.sfx", ".sfx", OK, 0},
    {"dir.sfx/file.very-long-suffix", ".very-long-suffix", OK, 0},
    {"dir.sfx/file.s", ".s", OK, 0},
    {"dir.sfx/file.", ".", OK, 0},
    {"dir.sfx/file", "<n/a>", ERR_SUFFIX, 0},
    {"dir.sfx/.file", "<n/a>", ERR_SUFFIX, 0},
    {"ⓓïȓ.şḟ𝓍/ḟïľē.şḟ𝓍", ".şḟ𝓍", OK, 0},
    {"ⓓïȓ.şḟ𝓍/ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", OK, 0},
    {"ⓓïȓ.şḟ𝓍/ḟïľē.ş", ".ş", OK, 0},
    {"ⓓïȓ.şḟ𝓍/ḟïľē.", ".", OK, 0},
    {"ⓓïȓ.şḟ𝓍/ḟïľē", "<n/a>", ERR_SUFFIX, 0},
    {"ⓓïȓ.şḟ𝓍/.ḟïľē", "<n/a>", ERR_SUFFIX, 0},
    {"/dir.sfx/file.sfx", ".sfx", OK, 0},
    {"/dir.sfx/file.very-long-suffix", ".very-long-suffix", OK, 0},
    {"/dir.sfx/file.s", ".s", OK, 0},
    {"/dir.sfx/file.", ".", OK, 0},
    {"/dir.sfx/file", "<n/a>", ERR_SUFFIX, 0},
    {"/dir.sfx/.file", "<n/a>", ERR_SUFFIX, 0},
    {"/ⓓïȓ.şḟ𝓍/ḟïľē.şḟ𝓍", ".şḟ𝓍", OK, 0},
    {"/ⓓïȓ.şḟ𝓍/ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", OK, 0},
    {"/ⓓïȓ.şḟ𝓍/ḟïľē.ş", ".ş", OK, 0},
    {"/ⓓïȓ.şḟ𝓍/ḟïľē.", ".", OK, 0},
    {"/ⓓïȓ.şḟ𝓍/ḟïľē", "<n/a>", ERR_SUFFIX, 0},
    {"/ⓓïȓ.şḟ𝓍/.ḟïľē", "<n/a>", ERR_SUFFIX, 0},
    {"./dir.sfx/file.sfx", ".sfx", OK, 0},
    {"./dir.sfx/file.very-long-suffix", ".very-long-suffix", OK, 0},
    {"./dir.sfx/file.s", ".s", OK, 0},
    {"./dir.sfx/file.", ".", OK, 0},
    {"./dir.sfx/file", "<n/a>", ERR_SUFFIX, 0},
    {"./dir.sfx/.file", "<n/a>", ERR_SUFFIX, 0},
    {"./ⓓïȓ.şḟ𝓍/ḟïľē.şḟ𝓍", ".şḟ𝓍", OK, 0},
    {"./ⓓïȓ.şḟ𝓍/ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", OK, 0},
    {"./ⓓïȓ.şḟ𝓍/ḟïľē.ş", ".ş", OK, 0},
    {"./ⓓïȓ.şḟ𝓍/ḟïľē.", ".", OK, 0},
    {"./ⓓïȓ.şḟ𝓍/ḟïľē", "<n/a>", ERR_SUFFIX, 0},
    {"./ⓓïȓ.şḟ𝓍/.ḟïľē", "<n/a>", ERR_SUFFIX, 0},
    {"../dir.sfx/file.sfx", ".sfx", OK, 0},
    {"../dir.sfx/file.very-long-suffix", ".very-long-suffix", OK, 0},
    {"../dir.sfx/file.s", ".s", OK, 0},
    {"../dir.sfx/file.", ".", OK, 0},
    {"../dir.sfx/file", "<n/a>", ERR_SUFFIX, 0},
    {"../dir.sfx/.file", "<n/a>", ERR_SUFFIX, 0},
    {"../ⓓïȓ.şḟ𝓍/ḟïľē.şḟ𝓍", ".şḟ𝓍", OK, 0},
    {"../ⓓïȓ.şḟ𝓍/ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", OK, 0},
    {"../ⓓïȓ.şḟ𝓍/ḟïľē.ş", ".ş", OK, 0},
    {"../ⓓïȓ.şḟ𝓍/ḟïľē.", ".", OK, 0},
    {"../ⓓïȓ.şḟ𝓍/ḟïľē", "<n/a>", ERR_SUFFIX, 0},
    {"../ⓓïȓ.şḟ𝓍/.ḟïľē", "<n/a>", ERR_SUFFIX, 0},
    {"dir/./file.sfx", ".sfx", OK, 0},
    {"dir/./file.very-long-suffix", ".very-long-suffix", OK, 0},
    {"dir/./file.s", ".s", OK, 0},
    {"dir/./file.", ".", OK, 0},
    {"dir/./file", "<n/a>", ERR_SUFFIX, 0},
    {"dir/./.file", "<n/a>", ERR_SUFFIX, 0},
    {"ⓓïȓ/./ḟïľē.şḟ𝓍", ".şḟ𝓍", OK, 0},
    {"ⓓïȓ/./ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", OK, 0},
    {"ⓓïȓ/./ḟïľē.ş", ".ş", OK, 0},
    {"ⓓïȓ/./ḟïľē.", ".", OK, 0},
    {"ⓓïȓ/./ḟïľē", "<n/a>", ERR_SUFFIX, 0},
    {"ⓓïȓ/./.ḟïľē", "<n/a>", ERR_SUFFIX, 0},
    {"/./dir/./file.sfx", ".sfx", OK, 0},
    {"/./dir/./file.very-long-suffix", ".very-long-suffix", OK, 0},
    {"/./dir/./file.s", ".s", OK, 0},
    {"/./dir/./file.", ".", OK, 0},
    {"/./dir/./file", "<n/a>", ERR_SUFFIX, 0},
    {"/./dir/./.file", "<n/a>", ERR_SUFFIX, 0},
    {"/./ⓓïȓ/./ḟïľē.şḟ𝓍", ".şḟ𝓍", OK, 0},
    {"/./ⓓïȓ/./ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", OK, 0},
    {"/./ⓓïȓ/./ḟïľē.ş", ".ş", OK, 0},
    {"/./ⓓïȓ/./ḟïľē.", ".", OK, 0},
    {"/./ⓓïȓ/./ḟïľē", "<n/a>", ERR_SUFFIX, 0},
    {"/./ⓓïȓ/./.ḟïľē", "<n/a>", ERR_SUFFIX, 0},
    {"././dir/./file.sfx", ".sfx", OK, 0},
    {"././dir/./file.very-long-suffix", ".very-long-suffix", OK, 0},
    {"././dir/./file.s", ".s", OK, 0},
    {"././dir/./file.", ".", OK, 0},
    {"././dir/./file", "<n/a>", ERR_SUFFIX, 0},
    {"././dir/./.file", "<n/a>", ERR_SUFFIX, 0},
    {"././ⓓïȓ/./ḟïľē.şḟ𝓍", ".şḟ𝓍", OK, 0},
    {"././ⓓïȓ/./ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", OK, 0},
    {"././ⓓïȓ/./ḟïľē.ş", ".ş", OK, 0},
    {"././ⓓïȓ/./ḟïľē.", ".", OK, 0},
    {"././ⓓïȓ/./ḟïľē", "<n/a>", ERR_SUFFIX, 0},
    {"././ⓓïȓ/./.ḟïľē", "<n/a>", ERR_SUFFIX, 0},
    {".././dir/./file.sfx", ".sfx", OK, 0},
    {".././dir/./file.very-long-suffix", ".very-long-suffix", OK, 0},
    {".././dir/./file.s", ".s", OK, 0},
    {".././dir/./file.", ".", OK, 0},
    {".././dir/./file", "<n/a>", ERR_SUFFIX, 0},
    {".././dir/./.file", "<n/a>", ERR_SUFFIX, 0},
    {".././ⓓïȓ/./ḟïľē.şḟ𝓍", ".şḟ𝓍", OK, 0},
    {".././ⓓïȓ/./ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", OK, 0},
    {".././ⓓïȓ/./ḟïľē.ş", ".ş", OK, 0},
    {".././ⓓïȓ/./ḟïľē.", ".", OK, 0},
    {".././ⓓïȓ/./ḟïľē", "<n/a>", ERR_SUFFIX, 0},
    {".././ⓓïȓ/./.ḟïľē", "<n/a>", ERR_SUFFIX, 0},
    {"dir.sfx/./file.sfx", ".sfx", OK, 0},
    {"dir.sfx/./file.very-long-suffix", ".very-long-suffix", OK, 0},
    {"dir.sfx/./file.s", ".s", OK, 0},
    {"dir.sfx/./file.", ".", OK, 0},
    {"dir.sfx/./file", "<n/a>", ERR_SUFFIX, 0},
    {"dir.sfx/./.file", "<n/a>", ERR_SUFFIX, 0},
    {"ⓓïȓ.şḟ𝓍/./ḟïľē.şḟ𝓍", ".şḟ𝓍", OK, 0},
    {"ⓓïȓ.şḟ𝓍/./ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", OK, 0},
    {"ⓓïȓ.şḟ𝓍/./ḟïľē.ş", ".ş", OK, 0},
    {"ⓓïȓ.şḟ𝓍/./ḟïľē.", ".", OK, 0},
    {"ⓓïȓ.şḟ𝓍/./ḟïľē", "<n/a>", ERR_SUFFIX, 0},
    {"ⓓïȓ.şḟ𝓍/./.ḟïľē", "<n/a>", ERR_SUFFIX, 0},
    {"/./dir.sfx/./file.sfx", ".sfx", OK, 0},
    {"/./dir.sfx/./file.very-long-suffix", ".very-long-suffix", OK, 0},
    {"/./dir.sfx/./file.s", ".s", OK, 0},
    {"/./dir.sfx/./file.", ".", OK, 0},
    {"/./dir.sfx/./file", "<n/a>", ERR_SUFFIX, 0},
    {"/./dir.sfx/./.file", "<n/a>", ERR_SUFFIX, 0},
    {"/./ⓓïȓ.şḟ𝓍/./ḟïľē.şḟ𝓍", ".şḟ𝓍", OK, 0},
    {"/./ⓓïȓ.şḟ𝓍/./ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", OK, 0},
    {"/./ⓓïȓ.şḟ𝓍/./ḟïľē.ş", ".ş", OK, 0},
    {"/./ⓓïȓ.şḟ𝓍/./ḟïľē.", ".", OK, 0},
    {"/./ⓓïȓ.şḟ𝓍/./ḟïľē", "<n/a>", ERR_SUFFIX, 0},
    {"/./ⓓïȓ.şḟ𝓍/./.ḟïľē", "<n/a>", ERR_SUFFIX, 0},
    {"././dir.sfx/./file.sfx", ".sfx", OK, 0},
    {"././dir.sfx/./file.very-long-suffix", ".very-long-suffix", OK, 0},
    {"././dir.sfx/./file.s", ".s", OK, 0},
    {"././dir.sfx/./file.", ".", OK, 0},
    {"././dir.sfx/./file", "<n/a>", ERR_SUFFIX, 0},
    {"././dir.sfx/./.file", "<n/a>", ERR_SUFFIX, 0},
    {"././ⓓïȓ.şḟ𝓍/./ḟïľē.şḟ𝓍", ".şḟ𝓍", OK, 0},
    {"././ⓓïȓ.şḟ𝓍/./ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", OK, 0},
    {"././ⓓïȓ.şḟ𝓍/./ḟïľē.ş", ".ş", OK, 0},
    {"././ⓓïȓ.şḟ𝓍/./ḟïľē.", ".", OK, 0},
    {"././ⓓïȓ.şḟ𝓍/./ḟïľē", "<n/a>", ERR_SUFFIX, 0},
    {"././ⓓïȓ.şḟ𝓍/./.ḟïľē", "<n/a>", ERR_SUFFIX, 0},
    {".././dir.sfx/./file.sfx", ".sfx", OK, 0},
    {".././dir.sfx/./file.very-long-suffix", ".very-long-suffix", OK, 0},
    {".././dir.sfx/./file.s", ".s", OK, 0},
    {".././dir.sfx/./file.", ".", OK, 0},
    {".././dir.sfx/./file", "<n/a>", ERR_SUFFIX, 0},
    {".././dir.sfx/./.file", "<n/a>", ERR_SUFFIX, 0},
    {".././ⓓïȓ.şḟ𝓍/./ḟïľē.şḟ𝓍", ".şḟ𝓍", OK, 0},
    {".././ⓓïȓ.şḟ𝓍/./ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", OK, 0},
    {".././ⓓïȓ.şḟ𝓍/./ḟïľē.ş", ".ş", OK, 0},
    {".././ⓓïȓ.şḟ𝓍/./ḟïľē.", ".", OK, 0},
    {".././ⓓïȓ.şḟ𝓍/./ḟïľē", "<n/a>", ERR_SUFFIX, 0},
    {".././ⓓïȓ.şḟ𝓍/./.ḟïľē", "<n/a>", ERR_SUFFIX, 0},
    {"/../dir/../file.sfx", ".sfx", OK, 0},
    {"/../dir/../file.very-long-suffix", ".very-long-suffix", OK, 0},
    {"/../dir/../file.s", ".s", OK, 0},
    {"/../dir/../file.", ".", OK, 0},
    {"/../dir/../file", "<n/a>", ERR_SUFFIX, 0},
    {"/../dir/../.file", "<n/a>", ERR_SUFFIX, 0},
    {"/../ⓓïȓ/../ḟïľē.şḟ𝓍", ".şḟ𝓍", OK, 0},
    {"/../ⓓïȓ/../ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", OK, 0},
    {"/../ⓓïȓ/../ḟïľē.ş", ".ş", OK, 0},
    {"/../ⓓïȓ/../ḟïľē.", ".", OK, 0},
    {"/../ⓓïȓ/../ḟïľē", "<n/a>", ERR_SUFFIX, 0},
    {"/../ⓓïȓ/../.ḟïľē", "<n/a>", ERR_SUFFIX, 0},
    {"./../dir/../file.sfx", ".sfx", OK, 0},
    {"./../dir/../file.very-long-suffix", ".very-long-suffix", OK, 0},
    {"./../dir/../file.s", ".s", OK, 0},
    {"./../dir/../file.", ".", OK, 0},
    {"./../dir/../file", "<n/a>", ERR_SUFFIX, 0},
    {"./../dir/../.file", "<n/a>", ERR_SUFFIX, 0},
    {"./../ⓓïȓ/../ḟïľē.şḟ𝓍", ".şḟ𝓍", OK, 0},
    {"./../ⓓïȓ/../ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", OK, 0},
    {"./../ⓓïȓ/../ḟïľē.ş", ".ş", OK, 0},
    {"./../ⓓïȓ/../ḟïľē.", ".", OK, 0},
    {"./../ⓓïȓ/../ḟïľē", "<n/a>", ERR_SUFFIX, 0},
    {"./../ⓓïȓ/../.ḟïľē", "<n/a>", ERR_SUFFIX, 0},
    {"../../dir/../file.sfx", ".sfx", OK, 0},
    {"../../dir/../file.very-long-suffix", ".very-long-suffix", OK, 0},
    {"../../dir/../file.s", ".s", OK, 0},
    {"../../dir/../file.", ".", OK, 0},
    {"../../dir/../file", "<n/a>", ERR_SUFFIX, 0},
    {"../../dir/../.file", "<n/a>", ERR_SUFFIX, 0},
    {"../../ⓓïȓ/../ḟïľē.şḟ𝓍", ".şḟ𝓍", OK, 0},
    {"../../ⓓïȓ/../ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", OK, 0},
    {"../../ⓓïȓ/../ḟïľē.ş", ".ş", OK, 0},
    {"../../ⓓïȓ/../ḟïľē.", ".", OK, 0},
    {"../../ⓓïȓ/../ḟïľē", "<n/a>", ERR_SUFFIX, 0},
    {"../../ⓓïȓ/../.ḟïľē", "<n/a>", ERR_SUFFIX, 0},
    {"dir.sfx/../file.sfx", ".sfx", OK, 0},
    {"dir.sfx/../file.very-long-suffix", ".very-long-suffix", OK, 0},
    {"dir.sfx/../file.s", ".s", OK, 0},
    {"dir.sfx/../file.", ".", OK, 0},
    {"dir.sfx/../file", "<n/a>", ERR_SUFFIX, 0},
    {"dir.sfx/../.file", "<n/a>", ERR_SUFFIX, 0},
    {"ⓓïȓ.şḟ𝓍/../ḟïľē.şḟ𝓍", ".şḟ𝓍", OK, 0},
    {"ⓓïȓ.şḟ𝓍/../ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", OK, 0},
    {"ⓓïȓ.şḟ𝓍/../ḟïľē.ş", ".ş", OK, 0},
    {"ⓓïȓ.şḟ𝓍/../ḟïľē.", ".", OK, 0},
    {"ⓓïȓ.şḟ𝓍/../ḟïľē", "<n/a>", ERR_SUFFIX, 0},
    {"ⓓïȓ.şḟ𝓍/../.ḟïľē", "<n/a>", ERR_SUFFIX, 0},
    {"/../dir.sfx/../file.sfx", ".sfx", OK, 0},
    {"/../dir.sfx/../file.very-long-suffix", ".very-long-suffix", OK, 0},
    {"/../dir.sfx/../file.s", ".s", OK, 0},
    {"/../dir.sfx/../file.", ".", OK, 0},
    {"/../dir.sfx/../file", "<n/a>", ERR_SUFFIX, 0},
    {"/../dir.sfx/../.file", "<n/a>", ERR_SUFFIX, 0},
    {"/../ⓓïȓ.şḟ𝓍/../ḟïľē.şḟ𝓍", ".şḟ𝓍", OK, 0},
    {"/../ⓓïȓ.şḟ𝓍/../ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", OK, 0},
    {"/../ⓓïȓ.şḟ𝓍/../ḟïľē.ş", ".ş", OK, 0},
    {"/../ⓓïȓ.şḟ𝓍/../ḟïľē.", ".", OK, 0},
    {"/../ⓓïȓ.şḟ𝓍/../ḟïľē", "<n/a>", ERR_SUFFIX, 0},
    {"/../ⓓïȓ.şḟ𝓍/../.ḟïľē", "<n/a>", ERR_SUFFIX, 0},
    {"./../dir.sfx/../file.sfx", ".sfx", OK, 0},
    {"./../dir.sfx/../file.very-long-suffix", ".very-long-suffix", OK, 0},
    {"./../dir.sfx/../file.s", ".s", OK, 0},
    {"./../dir.sfx/../file.", ".", OK, 0},
    {"./../dir.sfx/../file", "<n/a>", ERR_SUFFIX, 0},
    {"./../dir.sfx/../.file", "<n/a>", ERR_SUFFIX, 0},
    {"./../ⓓïȓ.şḟ𝓍/../ḟïľē.şḟ𝓍", ".şḟ𝓍", OK, 0},
    {"./../ⓓïȓ.şḟ𝓍/../ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", OK, 0},
    {"./../ⓓïȓ.şḟ𝓍/../ḟïľē.ş", ".ş", OK, 0},
    {"./../ⓓïȓ.şḟ𝓍/../ḟïľē.", ".", OK, 0},
    {"./../ⓓïȓ.şḟ𝓍/../ḟïľē", "<n/a>", ERR_SUFFIX, 0},
    {"./../ⓓïȓ.şḟ𝓍/../.ḟïľē", "<n/a>", ERR_SUFFIX, 0},
    {"../../dir.sfx/../file.sfx", ".sfx", OK, 0},
    {"../../dir.sfx/../file.very-long-suffix", ".very-long-suffix", OK, 0},
    {"../../dir.sfx/../file.s", ".s", OK, 0},
    {"../../dir.sfx/../file.", ".", OK, 0},
    {"../../dir.sfx/../file", "<n/a>", ERR_SUFFIX, 0},
    {"../../dir.sfx/../.file", "<n/a>", ERR_SUFFIX, 0},
    {"../../ⓓïȓ.şḟ𝓍/../ḟïľē.şḟ𝓍", ".şḟ𝓍", OK, 0},
    {"../../ⓓïȓ.şḟ𝓍/../ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍", OK, 0},
    {"../../ⓓïȓ.şḟ𝓍/../ḟïľē.ş", ".ş", OK, 0},
    {"../../ⓓïȓ.şḟ𝓍/../ḟïľē.", ".", OK, 0},
    {"../../ⓓïȓ.şḟ𝓍/../ḟïľē", "<n/a>", ERR_SUFFIX, 0},
    {"../../ⓓïȓ.şḟ𝓍/../.ḟïľē", "<n/a>", ERR_SUFFIX, 0},
    {".///", "<n/a>", ERR_SUFFIX, 0},
    {"////", "<n/a>", ERR_SUFFIX, 0},
    {"file.sfx///", ".sfx///", OK, 0},
    {"file.very-long-suffix///", ".very-long-suffix///", OK, 0},
    {"file.s///", ".s///", OK, 0},
    {"file.///", ".///", OK, 0},
    {"file///", "<n/a>", ERR_SUFFIX, 0},
    {".file///", "<n/a>", ERR_SUFFIX, 0},
    {"ḟïľē.şḟ𝓍///", ".şḟ𝓍///", OK, 0},
    {"ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", OK, 0},
    {"ḟïľē.ş///", ".ş///", OK, 0},
    {"ḟïľē.///", ".///", OK, 0},
    {"ḟïľē///", "<n/a>", ERR_SUFFIX, 0},
    {".ḟïľē///", "<n/a>", ERR_SUFFIX, 0},
    {"/file.sfx///", ".sfx///", OK, 0},
    {"/file.very-long-suffix///", ".very-long-suffix///", OK, 0},
    {"/file.s///", ".s///", OK, 0},
    {"/file.///", ".///", OK, 0},
    {"/file///", "<n/a>", ERR_SUFFIX, 0},
    {"/.file///", "<n/a>", ERR_SUFFIX, 0},
    {"/ḟïľē.şḟ𝓍///", ".şḟ𝓍///", OK, 0},
    {"/ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", OK, 0},
    {"/ḟïľē.ş///", ".ş///", OK, 0},
    {"/ḟïľē.///", ".///", OK, 0},
    {"/ḟïľē///", "<n/a>", ERR_SUFFIX, 0},
    {"/.ḟïľē///", "<n/a>", ERR_SUFFIX, 0},
    {"./file.sfx///", ".sfx///", OK, 0},
    {"./file.very-long-suffix///", ".very-long-suffix///", OK, 0},
    {"./file.s///", ".s///", OK, 0},
    {"./file.///", ".///", OK, 0},
    {"./file///", "<n/a>", ERR_SUFFIX, 0},
    {"./.file///", "<n/a>", ERR_SUFFIX, 0},
    {"./ḟïľē.şḟ𝓍///", ".şḟ𝓍///", OK, 0},
    {"./ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", OK, 0},
    {"./ḟïľē.ş///", ".ş///", OK, 0},
    {"./ḟïľē.///", ".///", OK, 0},
    {"./ḟïľē///", "<n/a>", ERR_SUFFIX, 0},
    {"./.ḟïľē///", "<n/a>", ERR_SUFFIX, 0},
    {"../file.sfx///", ".sfx///", OK, 0},
    {"../file.very-long-suffix///", ".very-long-suffix///", OK, 0},
    {"../file.s///", ".s///", OK, 0},
    {"../file.///", ".///", OK, 0},
    {"../file///", "<n/a>", ERR_SUFFIX, 0},
    {"../.file///", "<n/a>", ERR_SUFFIX, 0},
    {"../ḟïľē.şḟ𝓍///", ".şḟ𝓍///", OK, 0},
    {"../ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", OK, 0},
    {"../ḟïľē.ş///", ".ş///", OK, 0},
    {"../ḟïľē.///", ".///", OK, 0},
    {"../ḟïľē///", "<n/a>", ERR_SUFFIX, 0},
    {"../.ḟïľē///", "<n/a>", ERR_SUFFIX, 0},
    {"dir/file.sfx///", ".sfx///", OK, 0},
    {"dir/file.very-long-suffix///", ".very-long-suffix///", OK, 0},
    {"dir/file.s///", ".s///", OK, 0},
    {"dir/file.///", ".///", OK, 0},
    {"dir/file///", "<n/a>", ERR_SUFFIX, 0},
    {"dir/.file///", "<n/a>", ERR_SUFFIX, 0},
    {"ⓓïȓ/ḟïľē.şḟ𝓍///", ".şḟ𝓍///", OK, 0},
    {"ⓓïȓ/ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", OK, 0},
    {"ⓓïȓ/ḟïľē.ş///", ".ş///", OK, 0},
    {"ⓓïȓ/ḟïľē.///", ".///", OK, 0},
    {"ⓓïȓ/ḟïľē///", "<n/a>", ERR_SUFFIX, 0},
    {"ⓓïȓ/.ḟïľē///", "<n/a>", ERR_SUFFIX, 0},
    {"/dir/file.sfx///", ".sfx///", OK, 0},
    {"/dir/file.very-long-suffix///", ".very-long-suffix///", OK, 0},
    {"/dir/file.s///", ".s///", OK, 0},
    {"/dir/file.///", ".///", OK, 0},
    {"/dir/file///", "<n/a>", ERR_SUFFIX, 0},
    {"/dir/.file///", "<n/a>", ERR_SUFFIX, 0},
    {"/ⓓïȓ/ḟïľē.şḟ𝓍///", ".şḟ𝓍///", OK, 0},
    {"/ⓓïȓ/ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", OK, 0},
    {"/ⓓïȓ/ḟïľē.ş///", ".ş///", OK, 0},
    {"/ⓓïȓ/ḟïľē.///", ".///", OK, 0},
    {"/ⓓïȓ/ḟïľē///", "<n/a>", ERR_SUFFIX, 0},
    {"/ⓓïȓ/.ḟïľē///", "<n/a>", ERR_SUFFIX, 0},
    {"./dir/file.sfx///", ".sfx///", OK, 0},
    {"./dir/file.very-long-suffix///", ".very-long-suffix///", OK, 0},
    {"./dir/file.s///", ".s///", OK, 0},
    {"./dir/file.///", ".///", OK, 0},
    {"./dir/file///", "<n/a>", ERR_SUFFIX, 0},
    {"./dir/.file///", "<n/a>", ERR_SUFFIX, 0},
    {"./ⓓïȓ/ḟïľē.şḟ𝓍///", ".şḟ𝓍///", OK, 0},
    {"./ⓓïȓ/ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", OK, 0},
    {"./ⓓïȓ/ḟïľē.ş///", ".ş///", OK, 0},
    {"./ⓓïȓ/ḟïľē.///", ".///", OK, 0},
    {"./ⓓïȓ/ḟïľē///", "<n/a>", ERR_SUFFIX, 0},
    {"./ⓓïȓ/.ḟïľē///", "<n/a>", ERR_SUFFIX, 0},
    {"../dir/file.sfx///", ".sfx///", OK, 0},
    {"../dir/file.very-long-suffix///", ".very-long-suffix///", OK, 0},
    {"../dir/file.s///", ".s///", OK, 0},
    {"../dir/file.///", ".///", OK, 0},
    {"../dir/file///", "<n/a>", ERR_SUFFIX, 0},
    {"../dir/.file///", "<n/a>", ERR_SUFFIX, 0},
    {"../ⓓïȓ/ḟïľē.şḟ𝓍///", ".şḟ𝓍///", OK, 0},
    {"../ⓓïȓ/ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", OK, 0},
    {"../ⓓïȓ/ḟïľē.ş///", ".ş///", OK, 0},
    {"../ⓓïȓ/ḟïľē.///", ".///", OK, 0},
    {"../ⓓïȓ/ḟïľē///", "<n/a>", ERR_SUFFIX, 0},
    {"../ⓓïȓ/.ḟïľē///", "<n/a>", ERR_SUFFIX, 0},
    {"dir.sfx/file.sfx///", ".sfx///", OK, 0},
    {"dir.sfx/file.very-long-suffix///", ".very-long-suffix///", OK, 0},
    {"dir.sfx/file.s///", ".s///", OK, 0},
    {"dir.sfx/file.///", ".///", OK, 0},
    {"dir.sfx/file///", "<n/a>", ERR_SUFFIX, 0},
    {"dir.sfx/.file///", "<n/a>", ERR_SUFFIX, 0},
    {"ⓓïȓ.şḟ𝓍/ḟïľē.şḟ𝓍///", ".şḟ𝓍///", OK, 0},
    {"ⓓïȓ.şḟ𝓍/ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", OK, 0},
    {"ⓓïȓ.şḟ𝓍/ḟïľē.ş///", ".ş///", OK, 0},
    {"ⓓïȓ.şḟ𝓍/ḟïľē.///", ".///", OK, 0},
    {"ⓓïȓ.şḟ𝓍/ḟïľē///", "<n/a>", ERR_SUFFIX, 0},
    {"ⓓïȓ.şḟ𝓍/.ḟïľē///", "<n/a>", ERR_SUFFIX, 0},
    {"/dir.sfx/file.sfx///", ".sfx///", OK, 0},
    {"/dir.sfx/file.very-long-suffix///", ".very-long-suffix///", OK, 0},
    {"/dir.sfx/file.s///", ".s///", OK, 0},
    {"/dir.sfx/file.///", ".///", OK, 0},
    {"/dir.sfx/file///", "<n/a>", ERR_SUFFIX, 0},
    {"/dir.sfx/.file///", "<n/a>", ERR_SUFFIX, 0},
    {"/ⓓïȓ.şḟ𝓍/ḟïľē.şḟ𝓍///", ".şḟ𝓍///", OK, 0},
    {"/ⓓïȓ.şḟ𝓍/ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", OK, 0},
    {"/ⓓïȓ.şḟ𝓍/ḟïľē.ş///", ".ş///", OK, 0},
    {"/ⓓïȓ.şḟ𝓍/ḟïľē.///", ".///", OK, 0},
    {"/ⓓïȓ.şḟ𝓍/ḟïľē///", "<n/a>", ERR_SUFFIX, 0},
    {"/ⓓïȓ.şḟ𝓍/.ḟïľē///", "<n/a>", ERR_SUFFIX, 0},
    {"./dir.sfx/file.sfx///", ".sfx///", OK, 0},
    {"./dir.sfx/file.very-long-suffix///", ".very-long-suffix///", OK, 0},
    {"./dir.sfx/file.s///", ".s///", OK, 0},
    {"./dir.sfx/file.///", ".///", OK, 0},
    {"./dir.sfx/file///", "<n/a>", ERR_SUFFIX, 0},
    {"./dir.sfx/.file///", "<n/a>", ERR_SUFFIX, 0},
    {"./ⓓïȓ.şḟ𝓍/ḟïľē.şḟ𝓍///", ".şḟ𝓍///", OK, 0},
    {"./ⓓïȓ.şḟ𝓍/ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", OK, 0},
    {"./ⓓïȓ.şḟ𝓍/ḟïľē.ş///", ".ş///", OK, 0},
    {"./ⓓïȓ.şḟ𝓍/ḟïľē.///", ".///", OK, 0},
    {"./ⓓïȓ.şḟ𝓍/ḟïľē///", "<n/a>", ERR_SUFFIX, 0},
    {"./ⓓïȓ.şḟ𝓍/.ḟïľē///", "<n/a>", ERR_SUFFIX, 0},
    {"../dir.sfx/file.sfx///", ".sfx///", OK, 0},
    {"../dir.sfx/file.very-long-suffix///", ".very-long-suffix///", OK, 0},
    {"../dir.sfx/file.s///", ".s///", OK, 0},
    {"../dir.sfx/file.///", ".///", OK, 0},
    {"../dir.sfx/file///", "<n/a>", ERR_SUFFIX, 0},
    {"../dir.sfx/.file///", "<n/a>", ERR_SUFFIX, 0},
    {"../ⓓïȓ.şḟ𝓍/ḟïľē.şḟ𝓍///", ".şḟ𝓍///", OK, 0},
    {"../ⓓïȓ.şḟ𝓍/ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", OK, 0},
    {"../ⓓïȓ.şḟ𝓍/ḟïľē.ş///", ".ş///", OK, 0},
    {"../ⓓïȓ.şḟ𝓍/ḟïľē.///", ".///", OK, 0},
    {"../ⓓïȓ.şḟ𝓍/ḟïľē///", "<n/a>", ERR_SUFFIX, 0},
    {"../ⓓïȓ.şḟ𝓍/.ḟïľē///", "<n/a>", ERR_SUFFIX, 0},
    {"dir/./file.sfx///", ".sfx///", OK, 0},
    {"dir/./file.very-long-suffix///", ".very-long-suffix///", OK, 0},
    {"dir/./file.s///", ".s///", OK, 0},
    {"dir/./file.///", ".///", OK, 0},
    {"dir/./file///", "<n/a>", ERR_SUFFIX, 0},
    {"dir/./.file///", "<n/a>", ERR_SUFFIX, 0},
    {"ⓓïȓ/./ḟïľē.şḟ𝓍///", ".şḟ𝓍///", OK, 0},
    {"ⓓïȓ/./ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", OK, 0},
    {"ⓓïȓ/./ḟïľē.ş///", ".ş///", OK, 0},
    {"ⓓïȓ/./ḟïľē.///", ".///", OK, 0},
    {"ⓓïȓ/./ḟïľē///", "<n/a>", ERR_SUFFIX, 0},
    {"ⓓïȓ/./.ḟïľē///", "<n/a>", ERR_SUFFIX, 0},
    {"/./dir/./file.sfx///", ".sfx///", OK, 0},
    {"/./dir/./file.very-long-suffix///", ".very-long-suffix///", OK, 0},
    {"/./dir/./file.s///", ".s///", OK, 0},
    {"/./dir/./file.///", ".///", OK, 0},
    {"/./dir/./file///", "<n/a>", ERR_SUFFIX, 0},
    {"/./dir/./.file///", "<n/a>", ERR_SUFFIX, 0},
    {"/./ⓓïȓ/./ḟïľē.şḟ𝓍///", ".şḟ𝓍///", OK, 0},
    {"/./ⓓïȓ/./ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", OK, 0},
    {"/./ⓓïȓ/./ḟïľē.ş///", ".ş///", OK, 0},
    {"/./ⓓïȓ/./ḟïľē.///", ".///", OK, 0},
    {"/./ⓓïȓ/./ḟïľē///", "<n/a>", ERR_SUFFIX, 0},
    {"/./ⓓïȓ/./.ḟïľē///", "<n/a>", ERR_SUFFIX, 0},
    {"././dir/./file.sfx///", ".sfx///", OK, 0},
    {"././dir/./file.very-long-suffix///", ".very-long-suffix///", OK, 0},
    {"././dir/./file.s///", ".s///", OK, 0},
    {"././dir/./file.///", ".///", OK, 0},
    {"././dir/./file///", "<n/a>", ERR_SUFFIX, 0},
    {"././dir/./.file///", "<n/a>", ERR_SUFFIX, 0},
    {"././ⓓïȓ/./ḟïľē.şḟ𝓍///", ".şḟ𝓍///", OK, 0},
    {"././ⓓïȓ/./ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", OK, 0},
    {"././ⓓïȓ/./ḟïľē.ş///", ".ş///", OK, 0},
    {"././ⓓïȓ/./ḟïľē.///", ".///", OK, 0},
    {"././ⓓïȓ/./ḟïľē///", "<n/a>", ERR_SUFFIX, 0},
    {"././ⓓïȓ/./.ḟïľē///", "<n/a>", ERR_SUFFIX, 0},
    {".././dir/./file.sfx///", ".sfx///", OK, 0},
    {".././dir/./file.very-long-suffix///", ".very-long-suffix///", OK, 0},
    {".././dir/./file.s///", ".s///", OK, 0},
    {".././dir/./file.///", ".///", OK, 0},
    {".././dir/./file///", "<n/a>", ERR_SUFFIX, 0},
    {".././dir/./.file///", "<n/a>", ERR_SUFFIX, 0},
    {".././ⓓïȓ/./ḟïľē.şḟ𝓍///", ".şḟ𝓍///", OK, 0},
    {".././ⓓïȓ/./ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", OK, 0},
    {".././ⓓïȓ/./ḟïľē.ş///", ".ş///", OK, 0},
    {".././ⓓïȓ/./ḟïľē.///", ".///", OK, 0},
    {".././ⓓïȓ/./ḟïľē///", "<n/a>", ERR_SUFFIX, 0},
    {".././ⓓïȓ/./.ḟïľē///", "<n/a>", ERR_SUFFIX, 0},
    {"dir.sfx/./file.sfx///", ".sfx///", OK, 0},
    {"dir.sfx/./file.very-long-suffix///", ".very-long-suffix///", OK, 0},
    {"dir.sfx/./file.s///", ".s///", OK, 0},
    {"dir.sfx/./file.///", ".///", OK, 0},
    {"dir.sfx/./file///", "<n/a>", ERR_SUFFIX, 0},
    {"dir.sfx/./.file///", "<n/a>", ERR_SUFFIX, 0},
    {"ⓓïȓ.şḟ𝓍/./ḟïľē.şḟ𝓍///", ".şḟ𝓍///", OK, 0},
    {"ⓓïȓ.şḟ𝓍/./ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", OK, 0},
    {"ⓓïȓ.şḟ𝓍/./ḟïľē.ş///", ".ş///", OK, 0},
    {"ⓓïȓ.şḟ𝓍/./ḟïľē.///", ".///", OK, 0},
    {"ⓓïȓ.şḟ𝓍/./ḟïľē///", "<n/a>", ERR_SUFFIX, 0},
    {"ⓓïȓ.şḟ𝓍/./.ḟïľē///", "<n/a>", ERR_SUFFIX, 0},
    {"/./dir.sfx/./file.sfx///", ".sfx///", OK, 0},
    {"/./dir.sfx/./file.very-long-suffix///", ".very-long-suffix///", OK, 0},
    {"/./dir.sfx/./file.s///", ".s///", OK, 0},
    {"/./dir.sfx/./file.///", ".///", OK, 0},
    {"/./dir.sfx/./file///", "<n/a>", ERR_SUFFIX, 0},
    {"/./dir.sfx/./.file///", "<n/a>", ERR_SUFFIX, 0},
    {"/./ⓓïȓ.şḟ𝓍/./ḟïľē.şḟ𝓍///", ".şḟ𝓍///", OK, 0},
    {"/./ⓓïȓ.şḟ𝓍/./ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", OK, 0},
    {"/./ⓓïȓ.şḟ𝓍/./ḟïľē.ş///", ".ş///", OK, 0},
    {"/./ⓓïȓ.şḟ𝓍/./ḟïľē.///", ".///", OK, 0},
    {"/./ⓓïȓ.şḟ𝓍/./ḟïľē///", "<n/a>", ERR_SUFFIX, 0},
    {"/./ⓓïȓ.şḟ𝓍/./.ḟïľē///", "<n/a>", ERR_SUFFIX, 0},
    {"././dir.sfx/./file.sfx///", ".sfx///", OK, 0},
    {"././dir.sfx/./file.very-long-suffix///", ".very-long-suffix///", OK, 0},
    {"././dir.sfx/./file.s///", ".s///", OK, 0},
    {"././dir.sfx/./file.///", ".///", OK, 0},
    {"././dir.sfx/./file///", "<n/a>", ERR_SUFFIX, 0},
    {"././dir.sfx/./.file///", "<n/a>", ERR_SUFFIX, 0},
    {"././ⓓïȓ.şḟ𝓍/./ḟïľē.şḟ𝓍///", ".şḟ𝓍///", OK, 0},
    {"././ⓓïȓ.şḟ𝓍/./ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", OK, 0},
    {"././ⓓïȓ.şḟ𝓍/./ḟïľē.ş///", ".ş///", OK, 0},
    {"././ⓓïȓ.şḟ𝓍/./ḟïľē.///", ".///", OK, 0},
    {"././ⓓïȓ.şḟ𝓍/./ḟïľē///", "<n/a>", ERR_SUFFIX, 0},
    {"././ⓓïȓ.şḟ𝓍/./.ḟïľē///", "<n/a>", ERR_SUFFIX, 0},
    {".././dir.sfx/./file.sfx///", ".sfx///", OK, 0},
    {".././dir.sfx/./file.very-long-suffix///", ".very-long-suffix///", OK, 0},
    {".././dir.sfx/./file.s///", ".s///", OK, 0},
    {".././dir.sfx/./file.///", ".///", OK, 0},
    {".././dir.sfx/./file///", "<n/a>", ERR_SUFFIX, 0},
    {".././dir.sfx/./.file///", "<n/a>", ERR_SUFFIX, 0},
    {".././ⓓïȓ.şḟ𝓍/./ḟïľē.şḟ𝓍///", ".şḟ𝓍///", OK, 0},
    {".././ⓓïȓ.şḟ𝓍/./ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", OK, 0},
    {".././ⓓïȓ.şḟ𝓍/./ḟïľē.ş///", ".ş///", OK, 0},
    {".././ⓓïȓ.şḟ𝓍/./ḟïľē.///", ".///", OK, 0},
    {".././ⓓïȓ.şḟ𝓍/./ḟïľē///", "<n/a>", ERR_SUFFIX, 0},
    {".././ⓓïȓ.şḟ𝓍/./.ḟïľē///", "<n/a>", ERR_SUFFIX, 0},
    {"/../dir/../file.sfx///", ".sfx///", OK, 0},
    {"/../dir/../file.very-long-suffix///", ".very-long-suffix///", OK, 0},
    {"/../dir/../file.s///", ".s///", OK, 0},
    {"/../dir/../file.///", ".///", OK, 0},
    {"/../dir/../file///", "<n/a>", ERR_SUFFIX, 0},
    {"/../dir/../.file///", "<n/a>", ERR_SUFFIX, 0},
    {"/../ⓓïȓ/../ḟïľē.şḟ𝓍///", ".şḟ𝓍///", OK, 0},
    {"/../ⓓïȓ/../ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", OK, 0},
    {"/../ⓓïȓ/../ḟïľē.ş///", ".ş///", OK, 0},
    {"/../ⓓïȓ/../ḟïľē.///", ".///", OK, 0},
    {"/../ⓓïȓ/../ḟïľē///", "<n/a>", ERR_SUFFIX, 0},
    {"/../ⓓïȓ/../.ḟïľē///", "<n/a>", ERR_SUFFIX, 0},
    {"./../dir/../file.sfx///", ".sfx///", OK, 0},
    {"./../dir/../file.very-long-suffix///", ".very-long-suffix///", OK, 0},
    {"./../dir/../file.s///", ".s///", OK, 0},
    {"./../dir/../file.///", ".///", OK, 0},
    {"./../dir/../file///", "<n/a>", ERR_SUFFIX, 0},
    {"./../dir/../.file///", "<n/a>", ERR_SUFFIX, 0},
    {"./../ⓓïȓ/../ḟïľē.şḟ𝓍///", ".şḟ𝓍///", OK, 0},
    {"./../ⓓïȓ/../ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", OK, 0},
    {"./../ⓓïȓ/../ḟïľē.ş///", ".ş///", OK, 0},
    {"./../ⓓïȓ/../ḟïľē.///", ".///", OK, 0},
    {"./../ⓓïȓ/../ḟïľē///", "<n/a>", ERR_SUFFIX, 0},
    {"./../ⓓïȓ/../.ḟïľē///", "<n/a>", ERR_SUFFIX, 0},
    {"../../dir/../file.sfx///", ".sfx///", OK, 0},
    {"../../dir/../file.very-long-suffix///", ".very-long-suffix///", OK, 0},
    {"../../dir/../file.s///", ".s///", OK, 0},
    {"../../dir/../file.///", ".///", OK, 0},
    {"../../dir/../file///", "<n/a>", ERR_SUFFIX, 0},
    {"../../dir/../.file///", "<n/a>", ERR_SUFFIX, 0},
    {"../../ⓓïȓ/../ḟïľē.şḟ𝓍///", ".şḟ𝓍///", OK, 0},
    {"../../ⓓïȓ/../ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", OK, 0},
    {"../../ⓓïȓ/../ḟïľē.ş///", ".ş///", OK, 0},
    {"../../ⓓïȓ/../ḟïľē.///", ".///", OK, 0},
    {"../../ⓓïȓ/../ḟïľē///", "<n/a>", ERR_SUFFIX, 0},
    {"../../ⓓïȓ/../.ḟïľē///", "<n/a>", ERR_SUFFIX, 0},
    {"dir.sfx/../file.sfx///", ".sfx///", OK, 0},
    {"dir.sfx/../file.very-long-suffix///", ".very-long-suffix///", OK, 0},
    {"dir.sfx/../file.s///", ".s///", OK, 0},
    {"dir.sfx/../file.///", ".///", OK, 0},
    {"dir.sfx/../file///", "<n/a>", ERR_SUFFIX, 0},
    {"dir.sfx/../.file///", "<n/a>", ERR_SUFFIX, 0},
    {"ⓓïȓ.şḟ𝓍/../ḟïľē.şḟ𝓍///", ".şḟ𝓍///", OK, 0},
    {"ⓓïȓ.şḟ𝓍/../ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", OK, 0},
    {"ⓓïȓ.şḟ𝓍/../ḟïľē.ş///", ".ş///", OK, 0},
    {"ⓓïȓ.şḟ𝓍/../ḟïľē.///", ".///", OK, 0},
    {"ⓓïȓ.şḟ𝓍/../ḟïľē///", "<n/a>", ERR_SUFFIX, 0},
    {"ⓓïȓ.şḟ𝓍/../.ḟïľē///", "<n/a>", ERR_SUFFIX, 0},
    {"/../dir.sfx/../file.sfx///", ".sfx///", OK, 0},
    {"/../dir.sfx/../file.very-long-suffix///", ".very-long-suffix///", OK, 0},
    {"/../dir.sfx/../file.s///", ".s///", OK, 0},
    {"/../dir.sfx/../file.///", ".///", OK, 0},
    {"/../dir.sfx/../file///", "<n/a>", ERR_SUFFIX, 0},
    {"/../dir.sfx/../.file///", "<n/a>", ERR_SUFFIX, 0},
    {"/../ⓓïȓ.şḟ𝓍/../ḟïľē.şḟ𝓍///", ".şḟ𝓍///", OK, 0},
    {"/../ⓓïȓ.şḟ𝓍/../ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", OK, 0},
    {"/../ⓓïȓ.şḟ𝓍/../ḟïľē.ş///", ".ş///", OK, 0},
    {"/../ⓓïȓ.şḟ𝓍/../ḟïľē.///", ".///", OK, 0},
    {"/../ⓓïȓ.şḟ𝓍/../ḟïľē///", "<n/a>", ERR_SUFFIX, 0},
    {"/../ⓓïȓ.şḟ𝓍/../.ḟïľē///", "<n/a>", ERR_SUFFIX, 0},
    {"./../dir.sfx/../file.sfx///", ".sfx///", OK, 0},
    {"./../dir.sfx/../file.very-long-suffix///", ".very-long-suffix///", OK, 0},
    {"./../dir.sfx/../file.s///", ".s///", OK, 0},
    {"./../dir.sfx/../file.///", ".///", OK, 0},
    {"./../dir.sfx/../file///", "<n/a>", ERR_SUFFIX, 0},
    {"./../dir.sfx/../.file///", "<n/a>", ERR_SUFFIX, 0},
    {"./../ⓓïȓ.şḟ𝓍/../ḟïľē.şḟ𝓍///", ".şḟ𝓍///", OK, 0},
    {"./../ⓓïȓ.şḟ𝓍/../ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", OK, 0},
    {"./../ⓓïȓ.şḟ𝓍/../ḟïľē.ş///", ".ş///", OK, 0},
    {"./../ⓓïȓ.şḟ𝓍/../ḟïľē.///", ".///", OK, 0},
    {"./../ⓓïȓ.şḟ𝓍/../ḟïľē///", "<n/a>", ERR_SUFFIX, 0},
    {"./../ⓓïȓ.şḟ𝓍/../.ḟïľē///", "<n/a>", ERR_SUFFIX, 0},
    {"../../dir.sfx/../file.sfx///", ".sfx///", OK, 0},
    {"../../dir.sfx/../file.very-long-suffix///", ".very-long-suffix///", OK, 0},
    {"../../dir.sfx/../file.s///", ".s///", OK, 0},
    {"../../dir.sfx/../file.///", ".///", OK, 0},
    {"../../dir.sfx/../file///", "<n/a>", ERR_SUFFIX, 0},
    {"../../dir.sfx/../.file///", "<n/a>", ERR_SUFFIX, 0},
    {"../../ⓓïȓ.şḟ𝓍/../ḟïľē.şḟ𝓍///", ".şḟ𝓍///", OK, 0},
    {"../../ⓓïȓ.şḟ𝓍/../ḟïľē.𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", ".𝚟ēȓẙ-ľǭñģ-şüḟḟï𝓍///", OK, 0},
    {"../../ⓓïȓ.şḟ𝓍/../ḟïľē.ş///", ".ş///", OK, 0},
    {"../../ⓓïȓ.şḟ𝓍/../ḟïľē.///", ".///", OK, 0},
    {"../../ⓓïȓ.şḟ𝓍/../ḟïľē///", "<n/a>", ERR_SUFFIX, 0},
    {"../../ⓓïȓ.şḟ𝓍/../.ḟïľē///", "<n/a>", ERR_SUFFIX, 0}
};


/*
 * Main
 */

int
main (void)
{
    volatile int result = TEST_PASSED;

    checkinit();

#if !defined(NDEBUG)
    (void) memset(hugefname, 'x', sizeof(hugefname) - 1U);
#endif
    (void) memset(longfname, 'x', sizeof(longfname) - 1U);

    for (size_t i = 0; i < NELEMS(cases); ++i) {
        const Args args = cases[i];
        const char *suffix;
        int jumpval;
        Error retval;

        jumpval = sigsetjmp(checkenv, true);

        if (jumpval == 0) {
            checking = 1;
            retval = pathsuffix(args.fname, &suffix);
            checking = 0;

            if (retval != args.retval) {
                warnx("(%s, → %s) → %u [!]", args.fname, suffix, retval);
                result = TEST_FAILED;
            }

            if (retval == OK &&
                strncmp(args.suffix, suffix, MAX_SUFFIX_LEN) != 0)
            {
                warnx("(%s, → %s [!]) → %u", args.fname, suffix, retval);
                result = TEST_FAILED;
            }

        }

        if (jumpval != args.signo) {
            warnx("(%s, → %s [!]) ↑ %s",
                  args.fname, suffix, strsignal(jumpval));
            result = TEST_FAILED;
        }
    }

    return result;
}
