#!/bin/sh
# Run shell and compiler checks.
#
# Copyright 2022 Odin Kroeger.
#
# This file is part of suCGI.
#
# suCGI is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# suCGI is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along
# with suCGI. If not, see <https://www.gnu.org/licenses>.

# shellcheck disable=2015

#
# Defaults
#

# Shells to test.
readonly shells='sh bash dash ksh mksh oksh posh sash yash zsh'

# Arguments for check*.
args=


#
# Initialiation
#

set -Cefu
tools_dir="$(cd -P "$(dirname -- "$0")" && pwd)"
src_dir="$(dirname -- "$tools_dir")"
# shellcheck disable=2034
readonly tools_dir src_dir
# shellcheck disable=1091
. "$tools_dir/funcs.sh" || exit
init || exit


#
# Options
#

OPTIND=1 OPTARG='' opt=''
# shellcheck disable=2034
while getopts Dhqv opt; do
	# shellcheck disable=2154
	case $opt in
	(h) exec cat <<EOF
$prog_name - run shell and compiler checks

Usage:  $prog_name [-D] [-v]
        $prog_name -h

Options:
    -D  Show debugging information.
    -q  Be quieter.
    -v  Be verbose, but do not log runs.
    -h  Show this help screen.

Must be called from a directory with a makefile.
The makefile must provide the standard Autoconf targets.
EOF
	    ;;
	(D) args="$args -D" ;;
	(q) args="$args -q" ;;
	(v) args="$args -v" ;;
	(*) exit 1
	esac
done
shift $((OPTIND - 1))
unset opt

# shellcheck disable=2086
[ $# -eq 0 ] && set -- $shells


#
# Main
#

cd -P "$src_dir/scripts" || exit

# shellcheck disable=2086
./checkcomps $args
# shellcheck disable=2086
./checkmakes $args
# shellcheck disable=2086
./checkshells $args
