#!/bin/sh
# Run the test suite.
# shellcheck disable=2015

#
# Initialiation
#

set -u
readonly script_dir="${0%/*}"
# shellcheck disable=1091
. "$script_dir/utils.sh" || exit
init || exit


#
# Constants
#

# Number of child processes to spawn.
readonly nchildren=4



#
# Options
#

OPTIND=1 OPTARG='' opt=''
while getopts t:h opt; do
	case $opt in
		(t) export TESTSDIR="$OPTARG" ;;
		(h) exec cat <<-EOF ;;
			check - Run the test suite.

			Synopsis:
			    check [-t DIR] TEST [TEST [...]]
			    check -h

			Operands:
			    TEST  A test.

			Options:
			    -t DIR  Set \$TESTSDIR to DIR.
			    -h      Show this help screen.
			
			See README.md for details.
			EOF
		(*) exit 8
	esac
done
shift $((OPTIND - 1))
unset opt


#
# Main
#

[ $# -eq 0 ] && abort "no tests given."

errors=0 pids=
while [ $# -gt 0 ]; do
	name="$(basename "$1")" && [ "$name" ] ||
		abort "failed to get basename of $1."

	"$1" >/dev/null 2>&1 &
	pids="$pids $!"
	eval "test_$!"='$name'
	shift

	if [ $(($# % nchildren)) -eq 0 ]; then
		for pid in $pids; do
			eval name="\"\$test_$pid\""
			if ! wait "$pid"; then
				# shellcheck disable=2154
				warn "$red$bold$name$reset$red failed!$reset"
				errors=$((errors + 1))
			fi
		done
		pids=
	fi
done

# shellcheck disable=2154
[ "$errors" -eq 0 ] && warn "${green}all tests passed.$reset"

exit "$errors"
