#!/bin/sh
# Test a distribution.
# shellcheck disable=2015

#
# Initialiation
#

set -Cefu
readonly script_dir="${0%/*}"
# shellcheck disable=1091
. "$script_dir/utils.sh" || exit
init || exit
tmpdir dchk


#
# Options
#

OPTIND=1 OPTARG='' opt=''
while getopts a:h opt; do
	case $opt in
		(a) export ARCH="$OPTARG" ;;
		(h) exec cat <<-EOF ;;
			distcheck - Check if the tarball works

			Synopsis:
			    distcheck [-a ARCH] NAME
			    distcheck -h

			Operands:
			    NAME  Name of the directory to place files in.

			Options:
			    -a ARCH  Use ARCH as archive filename
			             (by default ".tgz" is appended to NAME).
			    -h       Show this help screen.
			
			See README.md for details.
			EOF
		(*) exit 8
	esac
done
shift $((OPTIND - 1))
unset opt

if [ $# -lt 1 ]
then
	echo 'usage: distcheck [-a ARCH] NAME' >&2
	exit 8
elif [ $# -gt 1 ]
then
	abort 'too many operands.'
fi

name="${1:?}"
: "${arch:="$name.tgz"}"


#
# Main
#

[ $# -gt 0 ] || abort "not enough operands." 

wd=$(pwd) && [ "$wd" ] || abort "failed to get working directory."
cd "$TMPDIR" || exit
"$wd/configure" -f
make dist
tar -xzf "$arch"
cleanup="chmod -R u+w \"\$TMPDIR\"; ${cleanup-}"
chmod -R ugo-w "$1"
"$name/configure"
make "$arch"
make
make check
chmod -R u+w .
make distclean
test ! -e makefile -a ! -e config.h -a ! -e build

# shellcheck disable=2154
warn "$green$bold$arch$reset$green passed.$reset"
