#!/bin/sh
# Create a distribution.

#
# Initialiation
#

set -Cefu
readonly script_dir="${0%/*}"
# shellcheck disable=1091
. "$script_dir/utils.sh" || exit
init || exit


#
# Options
#

OPTIND=1 OPTARG='' opt=''
while getopts a:h opt; do
	case $opt in
		(a) export arch="$OPTARG" ;;
		(h) exec cat <<-EOF ;;
			dist - Create a tarball for distribution.

			Synopsis:
			    dist [-a ARCH] NAME FILE [FILE [...]]
			    dist -h

			Operands:
			    NAME  Name of the directory to place files in.
			    FILE  A file to add to the distribution.

			Options:
			    -a ARCH  Use ARCH as archive filename
			             (by default ".tgz" is appended to NAME).
			    -h       Show this help screen.
			
			See README.md for details.
			EOF
		(*) exit 8
	esac
done
shift $((OPTIND - 1))
unset opt

if [ $# -lt 2 ]
then
	echo 'usage: dist [-a ARCH] NAME FILE [FILE [...]]' >&2
	exit 8
fi

name="${1:?}"
shift

: "${arch:="$name.tgz"}"


#
# Prelude
#

catch=
mkdir -m u=rwx,go= "$name"
cleanup="rm -rf \"\$name\"; ${cleanup-}"
# shellcheck disable=2034
catch=x
[ "${caught-}" ] && exit "$((caught + 128))"


#
# Main
#

cp -a "$@" "$name/"
chmod -R u+rw,go= "$name/"
tar -czf "$arch" "$name"
