#!/bin/sh
# Print the real user and group ID, even when running as root.
# shellcheck disable=1091,2015

#
# Initialisation
#

set -Cefu
readonly script_dir="${0%/*}"
# shellcheck disable=1091
. "$script_dir/utils.sh" || exit
init || exit
: "${TESTSDIR:=./build/tests}"
PATH="$TESTSDIR:$TESTSDIR/tools:$script_dir/../../build/tests:$PATH"
tmpdir ru


#
# Main
#

ruid="$(regularuid)" && [ "$ruid" ] ||
	abort 'failed to get non-root user ID.'

# FIXME: This is not in POSIX.1-2008.
rgid="$(id -g "$ruid")" && [ "$rgid" ] ||
	abort 'failed to get non-root group ID.'

printf '%d:%d\n' "$ruid" "$rgid"
