#!/bin/sh
# Print the current user's real user and group ID, even when running as root.
# shellcheck disable=1091,2015

#
# Initialisation
#

set -Cefu
readonly script_dir="${0%/*}"
# shellcheck disable=1091
. "$script_dir/utils.sh" || exit
init || exit
PATH="${TOOLSDIR:=./build/tests/tools}:$script_dir/../build/tests/tools:$PATH"
tmpdir ru


#
# Options
#

OPTIND=1 OPTARG='' opt=''
while getopts b:c:p:w:h opt; do
	case $opt in
		(h) exec cat <<-EOF ;;
			regularids - Print the user's regular UID and GID.

			Synopsis:
			    regularids

			Options:
			    -h         Show this help screen.
			EOF
		(*) exit 8
	esac
done
shift $((OPTIND - 1))
unset opt

[ $# -gt 0 ] && abort 'too many operands.'


#
# Main
#

ruid="$(regularuid)" && [ "$ruid" ] ||
	abort 'failed to get non-root user ID.'
user="$(username "$ruid")" && [ "$user" ] ||
	abort "failed to get username associated with ID $ruid."
rgid="$(id -g "$user")" && [ "$rgid" ] ||
	abort 'failed to get non-root group ID.'

printf '%d:%d\n' "$ruid" "$rgid"
