name: C/C++ CI

on:
  push:
    branches: [ "main", "release-*" ]
  pull_request:
    branches: [ "main", "release-*" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: sudo make check
      run: sudo make check
    - name: sudo make install
      run: sudo make WWWGRP=staff CGIBIN=. install
    - name: sudo make uninstall
      run: sudo make CGIBIN=. uninstall

