name: C/C++ CI

on:
  push:
    branches: [ "main", "release-*" ]
  pull_request:
    branches: [ "main", "release-*" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: CFLAGS= ./configure -f
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
