name: Codacy Coverage Reporter

on:
  push:
    branches: [ "main", "release-*" ]

jobs:
  codacy-coverage-reporter:
    permissions:
      contents: read
      security-events: read
    runs-on: ubuntu-22.04
    name: Codacy Coverage Reporter
    steps:
      - uses: actions/checkout@v3
      - name: sudo apt-get install lcov
        run: sudo apt-get install lcov
      - name: configure
        run: ./configure
      - name: make tools/badenv tools/ents tools/owner tools/runas
        run: make tools/badenv tools/ents tools/owner tools/runas
      - name: make CFLAGS="--coverage -O0 -g" check
        run: make CFLAGS="--coverage -O0 -g" check
      - name: sudo make CFLAGS="--coverage -O0 -g" check
        run: sudo make CFLAGS="--coverage -O0 -g" check
      - name: debug
        run: |
	    find . -name '*.gcda' -o -name '*.gcno' -exec chmod ugo+rw '{}' +
	    chown -R $(tools/owner .) .
	    chmod ugo+rx . .. ../.. ../../.. ../../../.. ../../../../..
#      - name: sudo make CFLAGS="--coverage -O0 -g" check
#        run: sudo make CFLAGS="--coverage -O0 -g" check
      - name: debug 2
        run: "find tests -type f ! -name '*.c' ! -name '*.h' -exec '{}' ';'"
      - name: "lcov -c -d . -o lcov.info --exclude '*/tests/*' --exclude '*/tools/*'"
        run: "lcov -c -d . -o lcov.info --exclude '*/tests/*' --exclude '*/tools/*'"
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: lcov.info
