name: Codacy Coverage Reporter

on:
  push:
    branches: [ "main", "release-*" ]

jobs:
  codacy-coverage-reporter:
    permissions:
      contents: read
      security-events: read
    runs-on: ubuntu-22.04
    name: Codacy Coverage Reporter
    steps:
      - uses: actions/checkout@v3
      - name: apt-get install lcov
        run: apt-get install lcov
      - name: configure
        run: CFLAGS= ./configure
      - name: make check
        run: make check
      - name: sudo make check
        run: sudo make check
      - name: sudo make lcov.info
        run: sudo make lcov.info
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: lcov.info
