name: Codacy Coverage Reporter

on:
  push:
    branches: [ "main", "release-*" ]

jobs:
  codacy-coverage-reporter:
    permissions:
      contents: read
      security-events: read
    runs-on: macos-latest
    name: codacy-coverage-reporter
    steps:
      - uses: actions/checkout@v3
      - name: Install lcov
        run: brew install lcov
      - name: configure
        run: CFLAGS= ./configure -f
      - name: make cov
        run: make cov
      - name: sudo make cov
        run: sudo make cov
      - name: sudo chmod -R o+r cov
        run: sudo chmod -R o+r cov
      - name: make lcov.info
        run: make lcov.info
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: lcov.info
