name: Codacy Coverage Reporter

on:
  push:
    branches: [ "devel", "main", "release-*" ]

jobs:
  codacy-coverage-reporter:
    permissions:
      contents: read
      security-events: read
    runs-on: macos-latest
    name: Codacy Coverage Reporter
    steps:
      - uses: actions/checkout@v3
      - name: Install LCOV
        run: brew install lcov
      - name: Create regular user
        run: sudo sysadminctl -addUser jdoe
      - name: Build
        run: |
            ./configure
            make all tools checks
            sudo make check
      - name: Generate coverage report
        run: sudo scripts/gencov -Llcov.info -H-
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: lcov.info
