name: macOS build 

on:
  push:
    branches: [ "main", "release-*" ]
  pull_request:
    branches: [ "main", "release-*" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: ./configure
      run: www_grp=staff cgi_dir=/tmp ./configure
    - name: cp config.h.sample config.h
      run: cp config.h.sample config.h
    - name: make
      run: make
    - name: make check
      run: 'make runpara_flags="-i75 -S" check'
    - name: sudo make check
      run: 'sudo make runpara_flags="-i75 -S" check'
    - name: sudo make install
      run: sudo make install
    - name: sudo make uninstall
      run: sudo make uninstall

