name: macOS build 

on:
  push:
    branches: [ "devel", "main", "release-*" ]
  pull_request:
    branches: [ "main", "release-*" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: ./configure
      run: ./configure
    - name: make all utils checks
      run: make all utils checks
    - name: sudo make check
      run: sudo make check runpara_flags=-Si75
    - name: sudo make install
      run: sudo make www_grp=staff cgi_dir=/tmp install
    - name: sudo make uninstall
      run: sudo make uninstall
    - name: make distcheck
      run: make distcheck runpara_flags=-Si75

