name: macOS build 

on:
  push:
    branches: [ "main", "release-*" ]
  pull_request:
    branches: [ "main", "release-*" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: ./configure
      run: www_grp=staff cgi_dir=/tmp ./configure
    - name: make
      run: make
    - name: test
      run: 'sudo sh tests/main.sh || :'
    - name: make check
      run: make check
    - name: sudo make check
      run: sudo make check
    - name: sudo make install
      run: sudo make install
    - name: sudo make uninstall
      run: sudo make uninstall

