name: SonarCloud

on:
  push:
    branches: [ "main", "release-*" ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - name: Build
      run: |
        ./configure
        make check
        sudo make check
        sudo make gcov
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0
          args: >
            -Dsonar.organization=odkr
            -Dsonar.projectKey=odkr_sucgi
            -Dsonar.cfamily.gcov.reportsPath=gcov
            -Dsonar.cfamily.cache.enabled=false

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
