#!/bin/sh

#
# Test BUG.
#
# Copyright 2022 Odin Kroeger.
#
# This file is part of suCGI.
#
# suCGI is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# suCGI is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General
# Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with suCGI. If not, see <https://www.gnu.org/licenses/>.
#


#
# Initialiation
#

set -Cefu
scripts_dir="$(cd -P "$(dirname -- "$0")" && pwd)"
: "${scripts_dir:?}"
readonly scripts_dir

src_dir="$(cd -P "$scripts_dir/../.." && pwd)"
: "${src_dir:?}"
readonly src_dir

# shellcheck disable=2154
export PATH="$src_dir/tests:$PATH"

# shellcheck disable=1091
. "$scripts_dir/libutil.sh"	|| exit
init				|| exit
tmpdir				|| exit

# Always exit with a status indicating failure unless $fin is set.
cleanup="${cleanup-:}; [ \"\${fin-}\" ] || exit 69"


#
# Globals
#

# Test result
result=0


#
# Options
#

OPTIND=1 OPTARG='' opt=''
while getopts Xh opt
do
	# shellcheck disable=2154
	case $opt in
	(h) exec cat <<EOF >&2
$progname - test error

Usage:  $progname [-X]
        $progname -h

Options:
    -X  Enable debugging.
    -h  Show this help screen.
EOF
            ;;
	(X) set -x ;;
	(*) exit 1
	esac
done
shift $((OPTIND - 1))
unset opt


#
# Messages
#

for arg in - foo bar baz
do
	check -s1 -e"$arg" BUG "$arg" || result=70
done


#
# Result
#

# shellcheck disable=2034
fin=y
exit "$result"
